#!/usr/bin/env bash
# =============================================================================
# overlay-source-helper.sh — cycle-099 Sprint 2C (T2.5)
# =============================================================================
# Helper functions for sourcing `.run/merged-model-aliases.sh` (the cycle-099
# Sprint 2B output) into a bash adapter's environment, with version-mismatch
# detection per Brief E.
#
# The merged file is generated by `.claude/scripts/lib/model-overlay-hook.py`
# on demand. When present and valid, it exposes five associative arrays
# (LOA_MODEL_PROVIDERS, LOA_MODEL_IDS, LOA_MODEL_ENDPOINT_FAMILIES,
# LOA_MODEL_COST_INPUT_PER_MTOK, LOA_MODEL_COST_OUTPUT_PER_MTOK) that include
# both framework defaults AND operator-added entries from
# `.loa.config.yaml::model_aliases_extra`. This is the operator-extras-aware
# resolution path, complementing the framework-only `model-resolver.sh`.
#
# # TRUST MODEL (read this before changing anything in here)
#
# `source` of any file is RCE by definition. The Sprint 2B writer
# (`model-overlay-hook.py`) is the SOLE legitimate writer of the merged
# file. The writer's hardening — atomic-rename, chmod 0600, O_NOFOLLOW on
# both the merged path and the lockfile, a shell-escape gate that uses
# `shlex.quote()` and rejects $/`/\/\n/\r — guarantees the file's content
# does NOT contain shell-metacharacter expansion vectors WHEN the writer
# emitted it.
#
# This helper's job is "do not weaken the writer's guarantees on read."
# Specifically:
#   - `bash -n` is a STRUCTURAL syntax check ONLY. It accepts content like
#     `[k]=$(rm -rf ~)` which IS a syntactically valid bash literal. The
#     defense is the writer's shell-escape gate, NOT the reader's `-n`.
#   - The content-shape gate added in iter-1 of cycle-099 sprint-2C dual
#     review (`_loa_overlay_validate_shape`) provides a SECONDARY defense:
#     the reader rejects any file whose body contains shapes the writer
#     never emits (e.g., command-substitution, semicolons, pipes,
#     non-allowlist characters in alias keys/values). This composes with
#     the writer's defenses to handle a tampered-after-rename scenario.
#   - The `LOA_OVERLAY_MERGED` and `LOA_OVERLAY_LOCKFILE` env-var overrides
#     are gated behind a 3-leg test-mode check (LOA_OVERLAY_HELPER_TEST_MODE
#     + the env var + BATS_VERSION OR PYTEST_CURRENT_TEST), mirroring the
#     Sprint 2B writer's own override gating. Production calls never see
#     attacker-controlled paths.
#
# Usage in a caller (e.g. `model-adapter.sh`):
#
#     # shellcheck source=lib/overlay-source-helper.sh
#     source "$SCRIPT_DIR/lib/overlay-source-helper.sh"
#     loa_overlay_init || true   # best-effort; framework resolver still works
#
#     # ... later, in the resolution chain:
#     if model_id="$(loa_overlay_resolve_provider_id "$alias" 2>/dev/null)"; then
#         : # operator-extras-aware path won
#     elif model_id="$(resolve_provider_id "$alias" 2>/dev/null)"; then
#         : # framework path won
#     ...
#
# Design constraints:
#   - Best-effort: if the merged file is missing or unreadable, the caller
#     falls through to existing resolution paths. We do NOT exit on init
#     failure — bash adapters that ran fine pre-cycle-099 must keep working.
#   - Defense-in-depth: bash syntax check (`bash -n`) AND content-shape
#     gate before sourcing.
#   - Shared flock briefly held during the read (matches cycle-099 SDD §6.3.1
#     loader contract: shared lock during multi-file reads avoids torn-read
#     racing against the writer's exclusive lock).
#   - Version-mismatch detection: caller can call loa_overlay_refresh_if_stale
#     between operations to pick up cross-process regen.
# =============================================================================

# Strict mode is the caller's choice; we don't enforce it because some legacy
# scripts source us under `set +e` and we shouldn't surprise them.

_OVERLAY_HELPER_LIB_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
_OVERLAY_HELPER_REPO_ROOT="$(cd "$_OVERLAY_HELPER_LIB_DIR/../../.." && pwd)"
_OVERLAY_HELPER_HOOK="$_OVERLAY_HELPER_LIB_DIR/model-overlay-hook.py"

# CYP-F3 fix: resolve python3 to an absolute path under a known-good prefix.
# An attacker-prepended $PATH must not redirect the hook invocation. We
# accept paths under /usr/, /usr/local/, /opt/, $HOME/.pyenv/, $HOME/.local/.
_loa_resolve_python3() {
    if [[ -x "/usr/bin/python3" ]]; then
        printf '%s' "/usr/bin/python3"
        return 0
    fi
    if [[ -x "/usr/local/bin/python3" ]]; then
        printf '%s' "/usr/local/bin/python3"
        return 0
    fi
    if command -v python3 &>/dev/null; then
        local resolved real
        resolved="$(command -v python3)"
        # Resolve symlinks; if realpath unavailable, use the resolved name as-is.
        real="$(realpath -e "$resolved" 2>/dev/null || printf '%s' "$resolved")"
        case "$real" in
            /usr/*|/opt/*|"$HOME"/.pyenv/*|"$HOME"/.local/*|/root/.pyenv/*|/root/.local/*)
                printf '%s' "$real"
                return 0
                ;;
        esac
    fi
    return 1
}
_OVERLAY_HELPER_PYTHON3="$(_loa_resolve_python3 || printf '')"

# CYP-F1 fix: 3-leg gate on env-var override of merged-file / lockfile paths.
# Mirrors Sprint 2B's `LOA_OVERLAY_PROC_MOUNTS_PATH_FOR_TEST` gating
# (model-overlay-hook.py::_resolve_test_proc_mounts_path):
#   1. LOA_OVERLAY_HELPER_TEST_MODE=1
#   2. LOA_OVERLAY_MERGED is set (the override itself)
#   3. BATS_VERSION OR PYTEST_CURRENT_TEST in env (proves test runner present)
# Partial gates (only one leg) MUST NOT escape — closes the env-var-leak
# footgun where an `.envrc` or CI variable bypasses production paths.
_loa_resolve_merged_path() {
    local default="$_OVERLAY_HELPER_REPO_ROOT/.run/merged-model-aliases.sh"
    local override="${LOA_OVERLAY_MERGED:-}"
    if [[ -z "$override" ]]; then
        printf '%s' "$default"
        return 0
    fi
    if [[ "${LOA_OVERLAY_HELPER_TEST_MODE:-}" != "1" ]]; then
        printf '%s' "$default"
        return 0
    fi
    if [[ -z "${BATS_VERSION:-}" && -z "${PYTEST_CURRENT_TEST:-}" ]]; then
        printf '%s' "$default"
        return 0
    fi
    printf '%s' "$override"
}

_loa_resolve_lockfile_path() {
    local default="$1.lock"   # caller passes the resolved merged path
    local override="${LOA_OVERLAY_LOCKFILE:-}"
    if [[ -z "$override" ]]; then
        printf '%s' "$default"
        return 0
    fi
    if [[ "${LOA_OVERLAY_HELPER_TEST_MODE:-}" != "1" ]]; then
        printf '%s' "$default"
        return 0
    fi
    if [[ -z "${BATS_VERSION:-}" && -z "${PYTEST_CURRENT_TEST:-}" ]]; then
        printf '%s' "$default"
        return 0
    fi
    printf '%s' "$override"
}

_OVERLAY_HELPER_MERGED="$(_loa_resolve_merged_path)"
_OVERLAY_HELPER_LOCKFILE="$(_loa_resolve_lockfile_path "$_OVERLAY_HELPER_MERGED")"

# CYP-F7 fix: lock the resolved paths so a subsequently-sourced library
# cannot reassign and hijack the hook invocation or merged-file source.
readonly _OVERLAY_HELPER_LIB_DIR _OVERLAY_HELPER_REPO_ROOT \
         _OVERLAY_HELPER_HOOK _OVERLAY_HELPER_PYTHON3 \
         _OVERLAY_HELPER_MERGED _OVERLAY_HELPER_LOCKFILE

# loa_overlay_read_version <file?> — read the `# version=N` header line from
# the merged file. Echoes the integer on success; returns 1 + empty stdout
# on missing file or unparseable header.
loa_overlay_read_version() {
    local file="${1:-$_OVERLAY_HELPER_MERGED}"
    [[ -f "$file" ]] || return 1
    local v
    # Match `# version=<digits>` only. Use awk that exits at first declare
    # so a future writer adding more header lines doesn't break us (CYP-F8 +
    # GP-F9 fix: replaces the previous `head -10` arbitrary cap).
    v="$(awk '
        /^declare/ { exit }
        /^# version=/ {
            sub(/^# version=/, "", $0)
            sub(/[[:space:]]*$/, "", $0)
            if ($0 ~ /^[0-9]+$/) { print $0; exit }
        }
    ' "$file" 2>/dev/null)"
    [[ -n "$v" ]] || return 1
    printf '%s' "$v"
}

# loa_overlay_read_source_sha <file?> — read the source-sha256 header. Used
# for cache-validity checks. Echoes the 64-char lowercase hex digest on
# success; returns 1 on missing file or unparseable header.
loa_overlay_read_source_sha() {
    local file="${1:-$_OVERLAY_HELPER_MERGED}"
    [[ -f "$file" ]] || return 1
    local s
    s="$(awk '
        /^declare/ { exit }
        /^# source-sha256=/ {
            sub(/^# source-sha256=/, "", $0)
            sub(/[[:space:]]*$/, "", $0)
            if ($0 ~ /^[0-9a-f]{64}$/) { print $0; exit }
        }
    ' "$file" 2>/dev/null)"
    [[ -n "$s" && ${#s} -eq 64 ]] || return 1
    printf '%s' "$s"
}

# _loa_overlay_invoke_hook — invoke the Sprint 2B hook to (re)generate
# the merged file. Best-effort: returns 0 on hook success, 1 on any failure.
# Caller decides whether to retry or fall through.
#
# GP-F1 fix: pass --merged + --lockfile so the hook writes to the same
# path the helper will read from. Previously the hook used its default
# `.run/merged-model-aliases.sh` regardless of the helper's override,
# causing test fixtures to pollute the developer's real `.run/` while
# the helper read from the override path.
#
# CYP-F3 fix: uses _OVERLAY_HELPER_PYTHON3 (absolute path resolved at
# source time), not bare `python3` from $PATH.
#
# GP-F3 fix: surface hook diagnostics when LOA_OVERLAY_DIAGNOSTICS=1, so
# operators investigating overlay drift can see [MODEL-EXTRA-INVALID] et al.
_loa_overlay_invoke_hook() {
    [[ -f "$_OVERLAY_HELPER_HOOK" ]] || return 1
    [[ -n "$_OVERLAY_HELPER_PYTHON3" ]] || return 1

    local stderr_redirect="/dev/null"
    if [[ "${LOA_OVERLAY_DIAGNOSTICS:-0}" == "1" ]]; then
        # Caller asked for diagnostics; let stderr through.
        stderr_redirect="/dev/stderr"
    fi
    "$_OVERLAY_HELPER_PYTHON3" "$_OVERLAY_HELPER_HOOK" \
        --merged "$_OVERLAY_HELPER_MERGED" \
        --lockfile "$_OVERLAY_HELPER_LOCKFILE" \
        2>"$stderr_redirect"
}

# _loa_overlay_validate_shape — CYP-F2 + CYP-F9 + CYP-F10 fix.
# Reject any line in the merged file that doesn't match the shape the
# writer (model-overlay-hook.py) actually emits. This is a defense-in-depth
# secondary gate; the primary defense is the writer's shell-escape gate +
# atomic-rename + chmod 0600 + O_NOFOLLOW.
#
# Allowed line shapes:
#   - empty line
#   - `^# ...` (header comment)
#   - `^declare -gA LOA_MODEL_(PROVIDERS|IDS|ENDPOINT_FAMILIES|COST_INPUT_PER_MTOK|COST_OUTPUT_PER_MTOK)=\($`
#   - `^[[:space:]]+\[[A-Za-z0-9._-]+\]=[A-Za-z0-9._-]+$`
#   - `^\)$`
#   - `^LOA_OVERLAY_FINGERPRINT=[a-f0-9]{12}$`
#
# REJECTS: command-substitution `$(...)`, backticks, parameter-expansion
# `${...:-...}`, semicolons, pipes, ampersands, redirects, newlines inside
# values, non-allowlist charset in keys/values/api_ids.
_loa_overlay_validate_shape() {
    local file="$1"
    [[ -f "$file" ]] || return 1
    awk '
        BEGIN {
            in_array = 0
            ok = 1
        }
        # Empty lines OK
        /^$/ { next }
        # Header comments OK
        /^#/ { next }
        # Array opener
        /^declare -gA LOA_MODEL_(PROVIDERS|IDS|ENDPOINT_FAMILIES|COST_INPUT_PER_MTOK|COST_OUTPUT_PER_MTOK)=\($/ {
            in_array = 1
            next
        }
        # Single-line empty array (e.g., `declare -gA X=()`)
        /^declare -gA LOA_MODEL_(PROVIDERS|IDS|ENDPOINT_FAMILIES|COST_INPUT_PER_MTOK|COST_OUTPUT_PER_MTOK)=\(\)$/ {
            next
        }
        # Array closer
        /^\)$/ {
            if (!in_array) { ok = 0; print "[OVERLAY-SHAPE-REJECT] unexpected close paren at line " NR > "/dev/stderr"; exit }
            in_array = 0
            next
        }
        # Array entry: leading whitespace + [key]=value, charset constrained
        /^[[:space:]]+\[[A-Za-z0-9._-]+\]=[A-Za-z0-9._-]+$/ {
            if (!in_array) { ok = 0; print "[OVERLAY-SHAPE-REJECT] entry outside array at line " NR > "/dev/stderr"; exit }
            next
        }
        # Fingerprint trailer
        /^LOA_OVERLAY_FINGERPRINT=[a-f0-9]{12}$/ {
            if (in_array) { ok = 0; print "[OVERLAY-SHAPE-REJECT] fingerprint inside array at line " NR > "/dev/stderr"; exit }
            next
        }
        # Anything else is a violation
        {
            ok = 0
            print "[OVERLAY-SHAPE-REJECT] unexpected line " NR ": " $0 > "/dev/stderr"
            exit
        }
        END {
            if (in_array) { print "[OVERLAY-SHAPE-REJECT] unclosed array at EOF" > "/dev/stderr"; ok = 0 }
            exit (ok ? 0 : 1)
        }
    ' "$file"
}

# _loa_overlay_canonical_path — CYP-F4 fix: resolve the merged-file path,
# refuse if it's a symlink, and refuse if the canonical path doesn't exist.
# Returns 0 + canonical path on success; returns 1 on rejection.
_loa_overlay_canonical_path() {
    local file="$_OVERLAY_HELPER_MERGED"
    [[ -e "$file" ]] || return 1
    if [[ -L "$file" ]]; then
        return 1   # refuse to follow symlinks at the merged path
    fi
    realpath -e "$file" 2>/dev/null || printf '%s' "$file"
}

# _loa_overlay_source_under_lock — source the merged file with a brief
# shared flock acquisition (matches SDD §6.3.4 multi-file-read contract).
# Falls back to plain `source` if flock(1) is unavailable (e.g., macOS
# without util-linux).
#
# CYP-F5 fix: refuse to open a symlinked lockfile (no O_NOFOLLOW in bash
# `exec <`, so we check `[[ -L ]]` first).
_loa_overlay_source_under_lock() {
    local file="$1"
    if command -v flock &>/dev/null && [[ -f "$_OVERLAY_HELPER_LOCKFILE" ]]; then
        if [[ -L "$_OVERLAY_HELPER_LOCKFILE" ]]; then
            # Symlinked lockfile is not the writer's product — refuse to
            # interact. Fall through to plain source (the merged-file
            # canonical-path check above handled the same surface).
            # shellcheck source=/dev/null
            source "$file"
            return $?
        fi
        # Use a high fd to avoid clashing with caller's redirections.
        # GP-F8 (LOW deferred): bash auto-fd `{var}<` would be cleaner but
        # is bash-4.1+; existing callers rely on bash 4.0 baseline.
        exec 9< "$_OVERLAY_HELPER_LOCKFILE"
        if flock -s -w 5 9 2>/dev/null; then
            # shellcheck source=/dev/null
            source "$file"
            local rc=$?
            flock -u 9 2>/dev/null || true
            exec 9<&-
            return $rc
        fi
        exec 9<&-
    fi
    # No flock available, or lockfile missing — source directly.
    # shellcheck source=/dev/null
    source "$file"
}

# loa_overlay_init — ensure the merged file exists, source it, capture
# the in-memory version. After successful init:
#   - LOA_MODEL_PROVIDERS / LOA_MODEL_IDS / LOA_MODEL_ENDPOINT_FAMILIES /
#     LOA_MODEL_COST_INPUT_PER_MTOK / LOA_MODEL_COST_OUTPUT_PER_MTOK
#     associative arrays are populated in the caller's shell
#   - LOA_OVERLAY_VERSION_AT_LOAD is set to the version integer
#   - LOA_OVERLAY_FINGERPRINT is set to the 12-char fingerprint
#
# Returns 0 on success; returns 1 if the merged file is unavailable AND
# the hook could not (re)generate it. Caller falls through to alternative
# resolution paths.
loa_overlay_init() {
    if [[ ! -f "$_OVERLAY_HELPER_MERGED" ]]; then
        # Try to generate via the hook. Best-effort.
        _loa_overlay_invoke_hook || return 1
    fi
    [[ -f "$_OVERLAY_HELPER_MERGED" ]] || return 1
    # CYP-F4: refuse symlinked merged file path
    if [[ -L "$_OVERLAY_HELPER_MERGED" ]]; then
        return 1
    fi
    # Defense-in-depth: structural syntax check
    bash -n "$_OVERLAY_HELPER_MERGED" 2>/dev/null || return 1
    # CYP-F2: secondary content-shape gate; rejects shapes the writer never emits
    _loa_overlay_validate_shape "$_OVERLAY_HELPER_MERGED" 2>/dev/null || return 1
    LOA_OVERLAY_VERSION_AT_LOAD="$(loa_overlay_read_version "$_OVERLAY_HELPER_MERGED")" || return 1
    # CYP-F6 fix: clear any pre-existing LOA_MODEL_* arrays before sourcing.
    # An attacker-poisoned environment could otherwise inject hostile entries
    # via pre-export, and a re-source after a stale-bump would merge old
    # entries with new ones (CYP-F12).
    unset LOA_MODEL_PROVIDERS LOA_MODEL_IDS LOA_MODEL_ENDPOINT_FAMILIES \
          LOA_MODEL_COST_INPUT_PER_MTOK LOA_MODEL_COST_OUTPUT_PER_MTOK
    unset LOA_OVERLAY_FINGERPRINT
    _loa_overlay_source_under_lock "$_OVERLAY_HELPER_MERGED" || return 1
    # CYP-F9 fix: validate fingerprint format post-source.
    if [[ -n "${LOA_OVERLAY_FINGERPRINT:-}" ]]; then
        if [[ ! "$LOA_OVERLAY_FINGERPRINT" =~ ^[a-f0-9]{12}$ ]]; then
            unset LOA_OVERLAY_FINGERPRINT
            return 1
        fi
    fi
    return 0
}

# loa_overlay_refresh_if_stale — re-read the on-disk version header.
# If it differs from LOA_OVERLAY_VERSION_AT_LOAD, the file was rewritten
# (cross-process regen), so re-source. Returns 0 whether or not a refresh
# was performed; returns 1 only if a refresh was attempted and failed.
#
# This is mostly relevant for long-running processes that source the
# overlay once at startup. Short-lived bash adapters usually exit before
# drift becomes detectable, but the check is cheap (header read only)
# so adding it is a defense against future cross-process integrations.
loa_overlay_refresh_if_stale() {
    [[ -n "${LOA_OVERLAY_VERSION_AT_LOAD:-}" ]] || return 0
    local on_disk
    on_disk="$(loa_overlay_read_version "$_OVERLAY_HELPER_MERGED")" || return 0
    if [[ "$on_disk" != "$LOA_OVERLAY_VERSION_AT_LOAD" ]]; then
        loa_overlay_init || return 1
    fi
    return 0
}

# CYP-F10 fix: the schema-allowed alias charset is `[A-Za-z0-9._-]+` per
# Sprint 2A. The writer-side validator rejects anything else, but the
# resolver functions also pre-validate to harden against log-injection
# (newlines, control bytes) and array-subscript edge cases (`]`, `[`).
_loa_overlay_validate_alias() {
    local alias="$1"
    [[ -n "$alias" ]] || return 1
    # NOTE: strict charset; mirrors SDD §3.5 rule 1 + Sprint 2A schema id pattern
    [[ "$alias" =~ ^[A-Za-z0-9._-]+$ ]] || return 1
    [[ "$alias" != *..* ]] || return 1   # cycle-099 dot-dot companion
    return 0
}

# loa_overlay_resolve_provider_id <alias> — lookup the alias in the
# overlay's LOA_MODEL_* arrays and emit `provider:api_id`. Returns 0 +
# stdout on hit; returns 1 (silent) on miss.
#
# The caller's resolution chain typically tries this FIRST (operator
# extras win), then falls back to model-resolver.sh::resolve_provider_id
# (framework only) on miss.
#
# Note on cross-reference (GP-F5): this function and
# `model-resolver.sh::resolve_provider_id` have the same signature but
# different data models. The framework version cross-checks resolved
# model_id against MODEL_PROVIDERS (registry consistency); this overlay
# version is per-alias-key only, since the overlay's bash arrays are
# authoritative-by-construction (the Python writer guarantees consistency).
loa_overlay_resolve_provider_id() {
    local alias="$1"
    _loa_overlay_validate_alias "$alias" || return 1
    if ! declare -p LOA_MODEL_PROVIDERS &>/dev/null; then
        return 1
    fi
    if ! declare -p LOA_MODEL_IDS &>/dev/null; then
        return 1
    fi
    local provider="${LOA_MODEL_PROVIDERS[$alias]:-}"
    local api_id="${LOA_MODEL_IDS[$alias]:-}"
    [[ -n "$provider" && -n "$api_id" ]] || return 1
    printf '%s:%s\n' "$provider" "$api_id"
}

# loa_overlay_resolve_alias <alias> — lookup just the alias→api_id mapping
# (without provider prefix). Mirrors model-resolver.sh::resolve_alias.
# Returns 0 + stdout on hit; returns 1 on miss.
loa_overlay_resolve_alias() {
    local alias="$1"
    _loa_overlay_validate_alias "$alias" || return 1
    if ! declare -p LOA_MODEL_IDS &>/dev/null; then
        return 1
    fi
    local api_id="${LOA_MODEL_IDS[$alias]:-}"
    [[ -n "$api_id" ]] || return 1
    printf '%s\n' "$api_id"
}

# loa_overlay_resolve_endpoint_family <alias> — lookup the endpoint family
# (chat / responses / messages / converse) for an alias. Returns 0 +
# stdout on hit; returns 1 on miss. Used by callers that need to route
# differently (e.g., openai responses vs chat).
loa_overlay_resolve_endpoint_family() {
    local alias="$1"
    _loa_overlay_validate_alias "$alias" || return 1
    if ! declare -p LOA_MODEL_ENDPOINT_FAMILIES &>/dev/null; then
        return 1
    fi
    local family="${LOA_MODEL_ENDPOINT_FAMILIES[$alias]:-}"
    [[ -n "$family" ]] || return 1
    printf '%s\n' "$family"
}
