/**
 * Simulated activity stream — fires synthetic WorldEvent-shaped events on a
 * 1.2-3.5s jittered interval against the synthetic-address pool generated by
 * lib/sim/entities.ts. Maintains a rolling buffer of recent events for
 * ActivityRail seed-render.
 *
 * Vocabulary mirrors the canonical `WorldEvent` union on the awareness branch
 * (see lib/activity/types.ts header for the schema cross-reference).
 *
 * Frequency weights — calibrated for "feels populated, not chatty":
 *   element_shift   50%   most common · the narrative beat of affinity drift
 *   quiz_completed  25%   the funnel · users discovering their archetype
 *   mint            20%   the conversion · genesis stone claim
 *   weather          5%   ambient · weather-tile already carries this signal
 */

import { ELEMENTS, type Element } from "@/lib/score";
import { OBSERVATORY_SPRITE_COUNT, syntheticAddress } from "@/lib/sim/entities";
import type {
  ActivityEvent,
  ActivityStream,
  ElementShiftActivity,
  MintActivity,
  OracleSource,
  QuizCompletedActivity,
  WeatherActivity,
} from "./types";

const BUFFER_SIZE = 100;

const buffer: ActivityEvent[] = [];
const subscribers = new Set<(e: ActivityEvent) => void>();
let intervalHandle: ReturnType<typeof setTimeout> | null = null;
let counter = 0;

// Wuxing 生 sheng (generation) cycle: wood → fire → earth → metal → water → wood.
const SHENG_NEXT: Record<Element, Element> = {
  wood: "fire",
  fire: "earth",
  earth: "metal",
  metal: "water",
  water: "wood",
};

const ORACLE_SOURCES: OracleSource[] = ["TREMOR", "CORONA", "BREATH"];

function pickFrom<T>(arr: readonly T[], r: number): T {
  return arr[Math.floor(r * arr.length) % arr.length];
}

function makeId(): string {
  return `e-${(++counter).toString(36)}-${Date.now().toString(36)}`;
}

// Build an affinity vector summing to 100 with the dominant element ahead.
function affinityWithDominant(
  dominant: Element,
  dominantPct: number,
): Record<Element, number> {
  const others = ELEMENTS.filter((e) => e !== dominant);
  const remainder = 100 - dominantPct;
  const raw = others.map(() => Math.random());
  const sum = raw.reduce((a, b) => a + b, 0);
  const result = {} as Record<Element, number>;
  result[dominant] = dominantPct;
  others.forEach((el, i) => {
    result[el] = Math.round((raw[i] / sum) * remainder);
  });
  // Reconcile rounding so total is exactly 100 — bias the slack onto the dominant.
  const total = ELEMENTS.reduce((s, el) => s + result[el], 0);
  result[dominant] += 100 - total;
  return result;
}

function buildMint(): MintActivity {
  const actorIdx = Math.floor(Math.random() * OBSERVATORY_SPRITE_COUNT);
  return {
    id: makeId(),
    kind: "mint",
    origin: "on-chain",
    actor: syntheticAddress(actorIdx + 1),
    element: pickFrom(ELEMENTS, Math.random()),
    weather: pickFrom(ELEMENTS, Math.random()),
    at: new Date().toISOString(),
  };
}

function buildElementShift(): ElementShiftActivity {
  const actorIdx = Math.floor(Math.random() * OBSERVATORY_SPRITE_COUNT);
  // Pick a "from" dominant, then a different "to" dominant — that's the shift.
  const fromDominant = pickFrom(ELEMENTS, Math.random());
  let toDominant = pickFrom(ELEMENTS, Math.random());
  if (toDominant === fromDominant) {
    toDominant = ELEMENTS[(ELEMENTS.indexOf(fromDominant) + 1) % ELEMENTS.length];
  }
  return {
    id: makeId(),
    kind: "element_shift",
    origin: "off-chain",
    actor: syntheticAddress(actorIdx + 1),
    element: toDominant,
    fromAffinity: affinityWithDominant(fromDominant, 45 + Math.floor(Math.random() * 20)),
    toAffinity: affinityWithDominant(toDominant, 45 + Math.floor(Math.random() * 20)),
    at: new Date().toISOString(),
  };
}

function buildQuizCompleted(): QuizCompletedActivity {
  return {
    id: makeId(),
    kind: "quiz_completed",
    origin: "off-chain",
    element: pickFrom(ELEMENTS, Math.random()),
    at: new Date().toISOString(),
  };
}

function buildWeather(): WeatherActivity {
  const dominant = pickFrom(ELEMENTS, Math.random());
  // 1-3 oracle sources · matches the awareness branch's array shape.
  const sourceCount = 1 + Math.floor(Math.random() * 3);
  const shuffled = [...ORACLE_SOURCES].sort(() => Math.random() - 0.5);
  return {
    id: makeId(),
    kind: "weather",
    origin: "off-chain",
    element: dominant,
    generativeNext: SHENG_NEXT[dominant],
    oracleSources: shuffled.slice(0, sourceCount),
    at: new Date().toISOString(),
  };
}

function randomEvent(): ActivityEvent {
  const r = Math.random();
  // Cumulative weights: element_shift 0.50, quiz_completed 0.75, mint 0.95, weather 1.00
  if (r < 0.5) return buildElementShift();
  if (r < 0.75) return buildQuizCompleted();
  if (r < 0.95) return buildMint();
  return buildWeather();
}

function emit(event: ActivityEvent): void {
  buffer.push(event);
  if (buffer.length > BUFFER_SIZE) buffer.shift();
  for (const cb of subscribers) {
    try {
      cb(event);
    } catch {
      // isolate subscriber errors
    }
  }
}

function scheduleNext(): void {
  if (typeof window === "undefined") return;
  // 1200ms - 3500ms jitter
  const delay = 1200 + Math.random() * 2300;
  intervalHandle = setTimeout(() => {
    emit(randomEvent());
    scheduleNext();
  }, delay);
}

function start(): void {
  if (intervalHandle !== null) return;
  if (typeof window === "undefined") return;
  // Seed buffer with a few past events so ActivityRail renders immediately
  if (buffer.length === 0) {
    const seedCount = 3;
    const baseTime = Date.now();
    for (let i = seedCount; i > 0; i--) {
      const e = randomEvent();
      // backdate by i*4 seconds so they look like "recent"
      e.at = new Date(baseTime - i * 4000).toISOString();
      buffer.push(e);
    }
  }
  scheduleNext();
}

function stop(): void {
  if (intervalHandle !== null) {
    clearTimeout(intervalHandle);
    intervalHandle = null;
  }
}

export const mockActivityStream: ActivityStream = {
  subscribe(cb: (e: ActivityEvent) => void): () => void {
    subscribers.add(cb);
    if (subscribers.size === 1) start();
    return () => {
      subscribers.delete(cb);
      if (subscribers.size === 0) stop();
    };
  },
  recent(n = 20): ActivityEvent[] {
    return buffer.slice(-n).reverse();
  },
};
