/**
 * Simulated activity stream — fires synthetic mint/attack/gift events
 * on a 1.2-3.5s jittered interval against the synthetic-address pool
 * generated by lib/sim/entities.ts. Maintains a rolling buffer of
 * recent events for ActivityRail seed-render.
 */

import { ELEMENTS, type Element } from "@/lib/score";
import { OBSERVATORY_SPRITE_COUNT, syntheticAddress } from "@/lib/sim/entities";
import type { ActionKind, ActivityEvent, ActivityStream } from "./types";

const KINDS: ActionKind[] = ["mint", "attack", "gift"];
const BUFFER_SIZE = 100;

const buffer: ActivityEvent[] = [];
const subscribers = new Set<(e: ActivityEvent) => void>();
let intervalHandle: ReturnType<typeof setTimeout> | null = null;
let counter = 0;

function pickFrom<T>(arr: readonly T[], r: number): T {
  return arr[Math.floor(r * arr.length) % arr.length];
}

function randomEvent(): ActivityEvent {
  const r1 = Math.random();
  const r2 = Math.random();
  const r3 = Math.random();
  const kind = pickFrom(KINDS, r1);
  const actorIdx = Math.floor(r2 * OBSERVATORY_SPRITE_COUNT);
  const actor = syntheticAddress(actorIdx + 1);
  const element = pickFrom(ELEMENTS, r3) as Element;

  const event: ActivityEvent = {
    id: `e-${(++counter).toString(36)}-${Date.now().toString(36)}`,
    kind,
    actor,
    element,
    at: new Date().toISOString(),
  };

  if (kind === "attack" || kind === "gift") {
    let targetIdx = Math.floor(Math.random() * OBSERVATORY_SPRITE_COUNT);
    if (targetIdx === actorIdx) targetIdx = (actorIdx + 1) % OBSERVATORY_SPRITE_COUNT;
    event.target = syntheticAddress(targetIdx + 1);
    let targetElement: Element = pickFrom(ELEMENTS, Math.random()) as Element;
    if (targetElement === element) {
      const next = (ELEMENTS.indexOf(element) + 1) % ELEMENTS.length;
      targetElement = ELEMENTS[next] as Element;
    }
    event.targetElement = targetElement;
  }

  return event;
}

function emit(event: ActivityEvent): void {
  buffer.push(event);
  if (buffer.length > BUFFER_SIZE) buffer.shift();
  for (const cb of subscribers) {
    try {
      cb(event);
    } catch {
      // isolate subscriber errors
    }
  }
}

function scheduleNext(): void {
  if (typeof window === "undefined") return;
  // 1200ms - 3500ms jitter
  const delay = 1200 + Math.random() * 2300;
  intervalHandle = setTimeout(() => {
    emit(randomEvent());
    scheduleNext();
  }, delay);
}

function start(): void {
  if (intervalHandle !== null) return;
  if (typeof window === "undefined") return;
  // Seed buffer with a few past events so ActivityRail renders immediately
  if (buffer.length === 0) {
    const seedCount = 3;
    const baseTime = Date.now();
    for (let i = seedCount; i > 0; i--) {
      const e = randomEvent();
      // backdate by i*4 seconds so they look like "recent"
      e.at = new Date(baseTime - i * 4000).toISOString();
      buffer.push(e);
    }
  }
  scheduleNext();
}

function stop(): void {
  if (intervalHandle !== null) {
    clearTimeout(intervalHandle);
    intervalHandle = null;
  }
}

export const mockActivityStream: ActivityStream = {
  subscribe(cb: (e: ActivityEvent) => void): () => void {
    subscribers.add(cb);
    if (subscribers.size === 1) start();
    return () => {
      subscribers.delete(cb);
      if (subscribers.size === 0) stop();
    };
  },
  recent(n = 20): ActivityEvent[] {
    return buffer.slice(-n).reverse();
  },
};
