/**
 * Simulated activity stream — fires synthetic "user joined [element]"
 * events on a 1.2-3.5s jittered interval against the synthetic-address
 * pool generated by lib/sim/entities.ts.
 *
 * Element selection is biased to the same favored-element rotation the
 * score adapter uses for clan-count distribution (see lib/score/mock.ts):
 * the dominant clan attracts ~34% of new joins, the next ~22%, tapering
 * down through the wuxing rotation. Keeps the rail coherent with the
 * KPI strip and the canvas — when the leader changes, the join trickle
 * follows over the next minute or two.
 */

import { ELEMENTS, type Element } from "@/lib/score";
import { OBSERVATORY_SPRITE_COUNT, syntheticAddress } from "@/lib/sim/entities";
import type { ActivityEvent, ActivityStream, JoinActivity } from "./types";

const BUFFER_SIZE = 100;

const buffer: ActivityEvent[] = [];
const subscribers = new Set<(e: ActivityEvent) => void>();
let intervalHandle: ReturnType<typeof setTimeout> | null = null;
let counter = 0;

// Mirrors lib/score/mock.ts RANK_SHARES — same distribution shape so the
// rail and the KPI clan counts agree on which element is winning.
const RANK_SHARES = [0.34, 0.22, 0.18, 0.15, 0.11];

function makeId(): string {
  return `e-${(++counter).toString(36)}-${Date.now().toString(36)}`;
}

function pickWeightedElement(): Element {
  // Same favored-element rotation as the score mock — full cycle ≈ 10min.
  const t = Date.now() / 1000;
  const favoredIdx = Math.floor((t / 120) % ELEMENTS.length);
  const r = Math.random();
  let acc = 0;
  for (let i = 0; i < ELEMENTS.length; i++) {
    const rank = (i - favoredIdx + ELEMENTS.length) % ELEMENTS.length;
    acc += RANK_SHARES[rank];
    if (r < acc) return ELEMENTS[i];
  }
  return ELEMENTS[ELEMENTS.length - 1];
}

function buildJoin(): JoinActivity {
  const actorIdx = Math.floor(Math.random() * OBSERVATORY_SPRITE_COUNT);
  return {
    id: makeId(),
    kind: "join",
    origin: "off-chain",
    actor: syntheticAddress(actorIdx + 1),
    element: pickWeightedElement(),
    at: new Date().toISOString(),
  };
}

function emit(event: ActivityEvent): void {
  buffer.push(event);
  if (buffer.length > BUFFER_SIZE) buffer.shift();
  for (const cb of subscribers) {
    try {
      cb(event);
    } catch {
      // isolate subscriber errors
    }
  }
}

function scheduleNext(): void {
  if (typeof window === "undefined") return;
  // 1200ms - 3500ms jitter
  const delay = 1200 + Math.random() * 2300;
  intervalHandle = setTimeout(() => {
    emit(buildJoin());
    scheduleNext();
  }, delay);
}

function start(): void {
  if (intervalHandle !== null) return;
  if (typeof window === "undefined") return;
  // Seed buffer with a few past events so ActivityRail renders immediately
  if (buffer.length === 0) {
    const seedCount = 3;
    const baseTime = Date.now();
    for (let i = seedCount; i > 0; i--) {
      const e = buildJoin();
      // backdate by i*4 seconds so they look like "recent"
      e.at = new Date(baseTime - i * 4000).toISOString();
      buffer.push(e);
    }
  }
  scheduleNext();
}

function stop(): void {
  if (intervalHandle !== null) {
    clearTimeout(intervalHandle);
    intervalHandle = null;
  }
}

export const mockActivityStream: ActivityStream = {
  subscribe(cb: (e: ActivityEvent) => void): () => void {
    subscribers.add(cb);
    if (subscribers.size === 1) start();
    return () => {
      subscribers.delete(cb);
      if (subscribers.size === 0) stop();
    };
  },
  recent(n = 20): ActivityEvent[] {
    return buffer.slice(-n).reverse();
  },
};

// Demo-bridge seed · pushes a curated JoinActivity into the stream so the
// post-mint loop closure ("your stone joined the lobby") is visible during
// demo recording when the real indexer (zerker's radar repo) isn't yet wired
// to push StoneClaimed events. Called by ObservatoryClient when ?welcome=
// query param is present. WEAVER+ROSENZU R4 audit · proof #4 needs visible
// arrival.
export function seedActivityEvent(event: ActivityEvent): void {
  emit(event);
}
