/**
 * Activity domain — the observatory's read-side of the awareness layer.
 *
 * v0 demo simplification (2026-05-10): the rail surfaces a single beat,
 * "[user] claimed [element] Stone" — a synthetic stand-in for the
 * canonical `QuizCompletedEvent` → `claim_genesis_stone` flow. The data
 * model still calls these `join` events because claiming a stone is
 * mechanically equivalent to joining that element's team. Mints /
 * weather / element-shifts are paused while the lifecycle layer is in
 * design; the feed reads as a continuous "new clan members are arriving"
 * stream that aligns with the canvas (sprites idle in their element
 * wedge) and the KPI strip (5 clan counts).
 *
 * When the lifecycle layer ships and the indexer wires in, additional
 * variants can be added back to the union below; ActivityEvent is kept
 * as a tagged union of size 1 so the rail's pattern-match shape stays.
 */

import type { Element, Wallet } from "@/lib/score";
import type { PuruhaniIdentity } from "@/lib/sim/types";

export type ActionOrigin = "on-chain" | "off-chain";

interface ActivityEventBase {
  id: string;
  origin: ActionOrigin;
  /** Drives row tint and avatar tint — the element the user just joined. */
  element: Element;
  at: string;
}

export interface JoinActivity extends ActivityEventBase {
  kind: "join";
  origin: "off-chain";
  /** Synthetic wallet of the user whose archetype just emerged. */
  actor: Wallet;
}

/**
 * On-chain `StoneClaimed` event surfaced by the radar Solana indexer
 * (see `project-purupuru/radar`). Structurally compatible with
 * JoinActivity at the rail's render surface (id/element/actor/at), with
 * additional provenance fields for traceability and dedup.
 *
 * Wired in 2026-05-10 per PRD AC-12.9. The rail does NOT branch on kind
 * — both variants present identically; the differentiator is `origin`
 * if a downstream consumer wants to filter or style.
 */
export interface MintActivity extends ActivityEventBase {
  kind: "mint";
  origin: "on-chain";
  /** Base58 Solana wallet that received the minted stone. */
  actor: Wallet;
  /** Base58 transaction signature; primary key for dedup. */
  signature: string;
  /** Log index within the transaction (handles multi-mint-per-tx). */
  logIndex: number;
  /** Solana slot the mint landed in. */
  slot: number;
  /** Weather element at mint time (separate from primary `element`). */
  weather: Element;
  /** Base58 mint address (the SPL token / NFT mint). */
  mint: string;
  /**
   * Deterministic puruhani identity (displayName, username, avatar)
   * generated by hashing `actor` to a stable seed and feeding through
   * the same `identityFor()` generator populationStore uses. Carried
   * inline on the event so the rail can render real mints with the
   * polished display treatment without round-tripping through any
   * shared registry.
   */
  identity: PuruhaniIdentity;
}

export type ActivityEvent = JoinActivity | MintActivity;

export type ActionKind = ActivityEvent["kind"];

export interface ActivityStream {
  subscribe(cb: (e: ActivityEvent) => void): () => void;
  recent(n?: number): ActivityEvent[];
}
