#!/usr/bin/env bats
bats_require_minimum_version 1.5.0
# =============================================================================
# model-adapter-overlay-source.bats — cycle-099 Sprint 2C (T2.5)
#
# End-to-end integration tests for `.claude/scripts/model-adapter.sh` sourcing
# the cycle-099 Sprint 2B `.run/merged-model-aliases.sh` overlay. Verifies:
#   - Operator-extras-aware resolution: aliases NOT in framework SoT but
#     present in the overlay resolve correctly via overlay path.
#   - Framework alias regression: well-known framework aliases (opus, reviewer)
#     still resolve when the overlay contains them too.
#   - Graceful degradation: missing merged file → adapter falls through to
#     model-resolver.sh path; legacy aliases still work.
# =============================================================================

setup() {
  REPO_ROOT="$(cd "$BATS_TEST_DIRNAME/../.." && pwd)"
  ADAPTER="$REPO_ROOT/.claude/scripts/model-adapter.sh"
  WORK="$(mktemp -d)"
  MERGED="$WORK/merged-model-aliases.sh"
  LOCKFILE="$MERGED.lock"
  INPUT="$WORK/input.txt"
  printf 'sample input\n' > "$INPUT"

  # CYP-F1 dual-review fix: 3-leg gate on env-var override
  export LOA_OVERLAY_HELPER_TEST_MODE=1
  export LOA_OVERLAY_MERGED="$MERGED"
  export LOA_OVERLAY_LOCKFILE="$LOCKFILE"
  export HOUNFOUR_FLATLINE_ROUTING=true   # exercise the v2.0 shim path
}

teardown() {
  rm -rf "$WORK"
}

# Fixture: write a merged file that includes operator-added aliases NOT in
# framework SoT, plus the canonical framework aliases.
_fixture_merged_with_operator_extras() {
  cat > "$MERGED" <<'EOF'
# Generated by .claude/scripts/lib/model-overlay-hook.py at 2026-05-06T00:00:00Z
# version=1
# source-sha256=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
# holder-pid=12345
# DO NOT EDIT — regenerate via `loa-overlay-hook regen`

declare -gA LOA_MODEL_PROVIDERS=(
  [opus]=anthropic
  [reviewer]=openai
  [operator-only-alias]=openai
)

declare -gA LOA_MODEL_IDS=(
  [opus]=claude-opus-4-7
  [reviewer]=gpt-5.5
  [operator-only-alias]=gpt-5.7-operator-extra
)

declare -gA LOA_MODEL_ENDPOINT_FAMILIES=(
  [opus]=messages
  [reviewer]=responses
  [operator-only-alias]=responses
)

declare -gA LOA_MODEL_COST_INPUT_PER_MTOK=(
  [opus]=5000000
  [reviewer]=5000000
  [operator-only-alias]=40000000
)

declare -gA LOA_MODEL_COST_OUTPUT_PER_MTOK=(
  [opus]=25000000
  [reviewer]=30000000
  [operator-only-alias]=200000000
)

LOA_OVERLAY_FINGERPRINT=0123456789ab
EOF
  : > "$LOCKFILE"
}

# -----------------------------------------------------------------------------
# A — Operator-extras-aware resolution (the new feature)
# -----------------------------------------------------------------------------

@test "A1: adapter logs overlay-resolved alias for operator-only entry" {
  _fixture_merged_with_operator_extras
  run --separate-stderr "$ADAPTER" \
    --model operator-only-alias --mode review \
    --input "$INPUT" --dry-run
  # The dry-run path will fail at model-invoke (the operator alias has no
  # backing model in the registry), but the adapter's stderr MUST log the
  # resolved value, proving overlay sourcing happened.
  [[ "$stderr" == *"Model: operator-only-alias → openai:gpt-5.7-operator-extra"* ]]
}

# -----------------------------------------------------------------------------
# B — Framework alias regression — opus / reviewer still resolve
# -----------------------------------------------------------------------------

@test "B1: framework alias 'opus' resolves through overlay" {
  _fixture_merged_with_operator_extras
  run --separate-stderr "$ADAPTER" \
    --model opus --mode review \
    --input "$INPUT" --dry-run
  [[ "$stderr" == *"Model: opus → anthropic:claude-opus-4-7"* ]]
}

@test "B2: framework alias 'reviewer' resolves through overlay" {
  _fixture_merged_with_operator_extras
  run --separate-stderr "$ADAPTER" \
    --model reviewer --mode review \
    --input "$INPUT" --dry-run
  [[ "$stderr" == *"Model: reviewer → openai:gpt-5.5"* ]]
}

# -----------------------------------------------------------------------------
# C — Graceful degradation: missing merged file
# -----------------------------------------------------------------------------

@test "C1: adapter still works when merged file is absent" {
  # Don't create the merged file. Set LOA_OVERLAY_MERGED to a bogus path
  # so the helper's hook-regen also fails (we don't want a real hook
  # invocation in this test).
  export LOA_OVERLAY_MERGED="$WORK/nonexistent-overlay.sh"
  export LOA_OVERLAY_LOCKFILE="$WORK/nonexistent-overlay.sh.lock"
  run --separate-stderr "$ADAPTER" \
    --model opus --mode review \
    --input "$INPUT" --dry-run
  # Resolution should still succeed via model-resolver.sh (framework canonical)
  [[ "$stderr" == *"Model: opus → anthropic:claude-opus-4-7"* ]]
}

# -----------------------------------------------------------------------------
# D — Hostile/corrupt overlay falls through gracefully
# -----------------------------------------------------------------------------

@test "D1: corrupt merged file (bash syntax error) → adapter still resolves via model-resolver" {
  # Make a syntactically invalid merged file
  cat > "$MERGED" <<'EOF'
# version=1
this is { bonkers (((
EOF
  : > "$LOCKFILE"
  run --separate-stderr "$ADAPTER" \
    --model opus --mode review \
    --input "$INPUT" --dry-run
  # loa_overlay_init refuses to source the syntactically-invalid file;
  # the adapter falls through to resolve_provider_id (framework canonical).
  [[ "$stderr" == *"Model: opus → anthropic:claude-opus-4-7"* ]]
}

# -----------------------------------------------------------------------------
# E — Overlay precedence over framework default
# -----------------------------------------------------------------------------

@test "E1: overlay-resolved alias takes precedence over framework default" {
  # Construct a merged file where 'opus' resolves to a DIFFERENT api_id
  # than the framework default. Verify the overlay's value wins.
  # NOTE: the cycle-099 Sprint 2A schema rejects collisions between
  # `model_aliases_extra` entries and framework-default IDs (IMP-004), so
  # this scenario is contrived — operators cannot produce it via
  # `.loa.config.yaml`. But the adapter's resolution chain still has overlay
  # FIRST, so this test pins that ordering for any future operator-override
  # surface (Sprint-2D `model_aliases_override`).
  cat > "$MERGED" <<'EOF'
# version=1
# source-sha256=bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
# holder-pid=99
# DO NOT EDIT

declare -gA LOA_MODEL_PROVIDERS=(
  [opus]=anthropic
)

declare -gA LOA_MODEL_IDS=(
  [opus]=claude-opus-4-7-OVERRIDDEN
)

declare -gA LOA_MODEL_ENDPOINT_FAMILIES=(
  [opus]=messages
)

declare -gA LOA_MODEL_COST_INPUT_PER_MTOK=(
  [opus]=1
)

declare -gA LOA_MODEL_COST_OUTPUT_PER_MTOK=(
  [opus]=1
)

LOA_OVERLAY_FINGERPRINT=cdef01234567
EOF
  : > "$LOCKFILE"
  run --separate-stderr "$ADAPTER" \
    --model opus --mode review \
    --input "$INPUT" --dry-run
  [[ "$stderr" == *"Model: opus → anthropic:claude-opus-4-7-OVERRIDDEN"* ]]
}

# -----------------------------------------------------------------------------
# F — Empty overlay file (parseable but no aliases) falls through
# -----------------------------------------------------------------------------

@test "F1: empty overlay arrays → adapter falls through to framework resolver" {
  cat > "$MERGED" <<'EOF'
# version=1
# source-sha256=cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
# holder-pid=99
# DO NOT EDIT
declare -gA LOA_MODEL_PROVIDERS=()
declare -gA LOA_MODEL_IDS=()
declare -gA LOA_MODEL_ENDPOINT_FAMILIES=()
declare -gA LOA_MODEL_COST_INPUT_PER_MTOK=()
declare -gA LOA_MODEL_COST_OUTPUT_PER_MTOK=()
LOA_OVERLAY_FINGERPRINT=eeee01234567
EOF
  : > "$LOCKFILE"
  run --separate-stderr "$ADAPTER" \
    --model opus --mode review \
    --input "$INPUT" --dry-run
  # Overlay arrays empty → loa_overlay_resolve_provider_id misses → falls
  # through to resolve_provider_id (framework). 'opus' resolves to canonical.
  [[ "$stderr" == *"Model: opus → anthropic:claude-opus-4-7"* ]]
}
