#!/bin/bash
#
# check-reality-freshness.sh - Check if reality files are fresh
#
# Usage: check-reality-freshness.sh [repo-path]
#
# Returns:
#   0 - Reality exists and is fresh (< 7 days)
#   1 - Reality exists but is stale (>= 7 days)
#   2 - No reality folder exists
#   3 - Reality exists but metadata is missing/invalid
#
# Output (JSON):
#   {"status": "fresh|stale|missing|invalid", "days_old": N, "generated_at": "...", "message": "..."}
#

set -euo pipefail

REPO_PATH="${1:-.}"
REALITY_DIR="$REPO_PATH/grimoires/loa/reality"
META_FILE="$REALITY_DIR/.reality-meta.json"
STALENESS_THRESHOLD=7

# Helper: Output JSON result
output_json() {
  local status="$1"
  local days_old="${2:-0}"
  local generated_at="${3:-}"
  local message="$4"

  cat <<EOF
{"status": "$status", "days_old": $days_old, "generated_at": "$generated_at", "message": "$message"}
EOF
}

# Check if reality folder exists
if [[ ! -d "$REALITY_DIR" ]]; then
  output_json "missing" 0 "" "No reality exists. Run /ride first to generate codebase analysis."
  exit 2
fi

# Check if index.md exists (minimum requirement)
if [[ ! -f "$REALITY_DIR/index.md" ]]; then
  output_json "invalid" 0 "" "Reality folder exists but index.md is missing. Re-run /ride."
  exit 3
fi

# Check for metadata file
if [[ ! -f "$META_FILE" ]]; then
  # Try to extract timestamp from index.md header
  HEADER_DATE=$(grep -oP "Generated by /ride on \K[0-9T:Z-]+" "$REALITY_DIR/index.md" 2>/dev/null || true)

  if [[ -z "$HEADER_DATE" ]]; then
    # Fall back to file modification time
    FILE_MTIME=$(stat -c %Y "$REALITY_DIR/index.md" 2>/dev/null || stat -f %m "$REALITY_DIR/index.md" 2>/dev/null || echo 0)
    NOW=$(date +%s)
    DAYS_OLD=$(( (NOW - FILE_MTIME) / 86400 ))

    if [[ $DAYS_OLD -ge $STALENESS_THRESHOLD ]]; then
      output_json "stale" "$DAYS_OLD" "" "Reality files were last modified $DAYS_OLD days ago (threshold: $STALENESS_THRESHOLD days). Consider re-running /ride."
      exit 1
    else
      output_json "fresh" "$DAYS_OLD" "" "Reality files are $DAYS_OLD days old (within threshold)."
      exit 0
    fi
  fi

  GENERATED_AT="$HEADER_DATE"
else
  # Parse metadata file
  if ! GENERATED_AT=$(jq -r '.generated_at // empty' "$META_FILE" 2>/dev/null); then
    output_json "invalid" 0 "" "Reality metadata exists but is not valid JSON."
    exit 3
  fi

  if [[ -z "$GENERATED_AT" ]]; then
    output_json "invalid" 0 "" "Reality metadata missing generated_at timestamp."
    exit 3
  fi
fi

# Calculate days since generation
GENERATED_EPOCH=$(date -d "$GENERATED_AT" +%s 2>/dev/null || date -j -f "%Y-%m-%dT%H:%M:%SZ" "$GENERATED_AT" +%s 2>/dev/null || echo 0)
NOW_EPOCH=$(date +%s)

if [[ $GENERATED_EPOCH -eq 0 ]]; then
  output_json "invalid" 0 "$GENERATED_AT" "Could not parse generation timestamp: $GENERATED_AT"
  exit 3
fi

DAYS_OLD=$(( (NOW_EPOCH - GENERATED_EPOCH) / 86400 ))

# Check staleness
if [[ $DAYS_OLD -ge $STALENESS_THRESHOLD ]]; then
  output_json "stale" "$DAYS_OLD" "$GENERATED_AT" "Reality files were generated $DAYS_OLD days ago (threshold: $STALENESS_THRESHOLD days). Consider re-running /ride for fresh analysis."
  exit 1
else
  output_json "fresh" "$DAYS_OLD" "$GENERATED_AT" "Reality files are $DAYS_OLD days old (within $STALENESS_THRESHOLD day threshold)."
  exit 0
fi
