#!/usr/bin/env bash
# =============================================================================
# gen-adapter-maps.sh — YAML → bash adapter map generator (vision-011, #548)
# =============================================================================
# Reads .claude/defaults/model-config.yaml and emits a bash script populating
# the four associative arrays consumed by model-adapter.sh.legacy:
#
#   MODEL_PROVIDERS  — model alias → provider name
#   MODEL_IDS        — model alias → canonical provider model ID
#   COST_INPUT       — model alias → USD per 1K input tokens
#   COST_OUTPUT     — model alias → USD per 1K output tokens
#
# Intent: eliminate hand-maintained bash maps that drift across model
# migrations. YAML becomes the single source of truth.
#
# Output: `.claude/scripts/generated-model-maps.sh` (overwrites).
#
# Usage:
#   gen-adapter-maps.sh                  # write to default output
#   gen-adapter-maps.sh --output <path>  # custom output file
#   gen-adapter-maps.sh --dry-run        # emit to stdout, no file write
#   gen-adapter-maps.sh --check          # exit 3 if output is stale vs YAML
#
# Exit codes:
#   0  success
#   1  yaml parse error / invalid config
#   2  usage error
#   3  --check mode: drift detected
# =============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="${PROJECT_ROOT:-$(cd "$SCRIPT_DIR/../.." && pwd)}"

CONFIG_FILE="${LOA_MODEL_CONFIG:-$PROJECT_ROOT/.claude/defaults/model-config.yaml}"
OUTPUT_FILE="${LOA_GENERATED_MAPS:-$PROJECT_ROOT/.claude/scripts/generated-model-maps.sh}"
DRY_RUN=false
CHECK=false

while [[ $# -gt 0 ]]; do
    case "$1" in
        --output)
            if [[ $# -lt 2 ]]; then echo "ERROR: --output requires a path" >&2; exit 2; fi
            OUTPUT_FILE="$2"; shift 2 ;;
        --dry-run) DRY_RUN=true; shift ;;
        --check) CHECK=true; shift ;;
        --config)
            if [[ $# -lt 2 ]]; then echo "ERROR: --config requires a path" >&2; exit 2; fi
            CONFIG_FILE="$2"; shift 2 ;;
        -h|--help)
            sed -n '2,/^$/p' "${BASH_SOURCE[0]}" | sed 's/^# \?//'
            exit 0 ;;
        *) echo "Unknown arg: $1" >&2; exit 2 ;;
    esac
done

if [[ ! -f "$CONFIG_FILE" ]]; then
    echo "ERROR: config file not found: $CONFIG_FILE" >&2
    exit 1
fi

if ! command -v yq >/dev/null 2>&1; then
    echo "ERROR: yq (v4+) is required but not on PATH" >&2
    exit 1
fi

if ! command -v jq >/dev/null 2>&1; then
    echo "ERROR: jq is required but not on PATH" >&2
    exit 1
fi

# YAML carries micro-USD per million tokens (5000 = $5/Mtok).
# Bash legacy carries USD per 1K tokens (0.005).
# Conversion: micro_per_mtok / 1_000_000 = USD per 1K tokens.
# Verification: 5000/1M = 0.005 ✓ ; 1_250_000/1M = 1.25 — but docs say
# gemini-2.5-pro is $1.25/MTok = $0.00125/1K. So divisor is actually
# 1_000_000 when YAML unit is micro-USD-per-MTok. 1_250_000 micro-USD-per-
# MTok = $1.25/MTok = $0.00125/1K tokens. 1_250_000 / 1_000_000_000 = 0.00125. Fixed.
_micro_usd_to_per_1k() {
    local micro="$1"
    awk -v m="$micro" 'BEGIN { printf "%g", m / 1000000000 }'
}

generate() {
    local now
    now=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

    # Pre-flight: detect duplicate keys across aliases + backward_compat_aliases.
    # Bash last-write-wins so behavior is safe, but duplicates are unnecessary
    # noise and may indicate an editor mistake. Warn to stderr; don't fail.
    local aliases_json compat_json dup_keys
    aliases_json=$(yq eval -o=json '.aliases // {}' "$CONFIG_FILE")
    compat_json=$(yq eval -o=json '.backward_compat_aliases // {}' "$CONFIG_FILE")
    dup_keys=$(jq -r --argjson a "$aliases_json" --argjson c "$compat_json" -n \
        '($a | keys) + ($c | keys) | group_by(.) | map(select(length > 1) | .[0]) | .[]' \
        2>/dev/null || true)
    if [[ -n "$dup_keys" ]]; then
        while IFS= read -r key; do
            echo "WARN: key '$key' appears in both aliases and backward_compat_aliases (last-write-wins, but remove duplicate for clarity)" >&2
        done <<< "$dup_keys"
    fi

    cat <<EOF
#!/usr/bin/env bash
# =============================================================================
# generated-model-maps.sh — DO NOT EDIT BY HAND
# =============================================================================
# Generated by .claude/scripts/gen-adapter-maps.sh from
# .claude/defaults/model-config.yaml. The YAML is the single source of truth.
#
# To regenerate: bash .claude/scripts/gen-adapter-maps.sh
# To check for drift: bash .claude/scripts/gen-adapter-maps.sh --check
# =============================================================================

declare -A MODEL_PROVIDERS=(
EOF

    yq eval -o=json '.providers' "$CONFIG_FILE" | jq -r '
        to_entries[] as $p
        | $p.value.models | to_entries[] as $m
        | "    [\"\($m.key)\"]=\"\($p.key)\""
    '

    yq eval -o=json '.aliases // {}' "$CONFIG_FILE" | jq -r '
        to_entries[]
        | select((.value | split(":")[0]) != "claude-code")
        | select(.value | test("^[^:]+:"))
        | "    [\"\(.key)\"]=\"\(.value | split(":")[0])\""
    '

    yq eval -o=json '.backward_compat_aliases // {}' "$CONFIG_FILE" | jq -r '
        to_entries[]
        | "    [\"\(.key)\"]=\"\(.value | split(":")[0])\""
    '

    cat <<EOF
)

declare -A MODEL_IDS=(
EOF

    yq eval -o=json '.providers' "$CONFIG_FILE" | jq -r '
        to_entries[] as $p
        | $p.value.models | to_entries[] as $m
        | "    [\"\($m.key)\"]=\"\($m.key)\""
    '

    yq eval -o=json '.aliases // {}' "$CONFIG_FILE" | jq -r '
        to_entries[]
        | select((.value | split(":")[0]) != "claude-code")
        | select(.value | test("^[^:]+:"))
        | "    [\"\(.key)\"]=\"\(.value | (split(":")[1:] | join(":")))\""
    '

    yq eval -o=json '.backward_compat_aliases // {}' "$CONFIG_FILE" | jq -r '
        to_entries[]
        | "    [\"\(.key)\"]=\"\(.value | (split(":")[1:] | join(":")))\""
    '

    cat <<EOF
)

declare -A COST_INPUT=(
EOF

    _emit_cost_map "input_per_mtok"

    cat <<EOF
)

declare -A COST_OUTPUT=(
EOF

    _emit_cost_map "output_per_mtok"

    cat <<EOF
)

# VALID_FLATLINE_MODELS — Sprint-4 T4.2 (closes SDD §1.4 C4 SSOT coverage gap).
# Hand-maintained array in flatline-orchestrator.sh historically drifted from
# the YAML during model migrations (cycle-082, cycle-093). Now derived from
# the same source-of-truth as MODEL_PROVIDERS / MODEL_IDS / COST_*.
#
# Contents: union of provider model IDs + aliases + backward-compat aliases.
# Excludes claude-code: synthetic provider (Claude Code native runtime).
declare -a VALID_FLATLINE_MODELS=(
EOF

    _emit_flatline_allowlist

    cat <<EOF
)
EOF
}

_emit_flatline_allowlist() {
    # Concatenate canonical model IDs across all providers, plus alias keys
    # and backward-compat alias keys. Sort + dedupe for deterministic output.
    {
        yq eval -o=json '.providers' "$CONFIG_FILE" | jq -r '
            to_entries[] as $p
            | $p.value.models | keys[]
        '
        yq eval -o=json '.aliases // {}' "$CONFIG_FILE" | jq -r '
            to_entries[]
            | select((.value | split(":")[0]) != "claude-code")
            | select(.value | test("^[^:]+:"))
            | .key
        '
        yq eval -o=json '.backward_compat_aliases // {}' "$CONFIG_FILE" | jq -r '
            to_entries[] | .key
        '
    } | sort -u | while IFS= read -r model; do
        [[ -z "$model" ]] && continue
        printf '    %s\n' "$model"
    done
}

_emit_cost_map() {
    local field="$1"

    yq eval -o=json '.providers' "$CONFIG_FILE" | jq -r --arg f "$field" '
        to_entries[] as $p
        | $p.value.models | to_entries[] as $m
        | "\($m.key)\t\($m.value.pricing[$f] // 0)"
    ' | while IFS=$'\t' read -r model micro; do
        # Note: variables inside piped `while` run in a subshell; no `local`
        # needed (and avoids a portability pitfall on older bash). The subshell
        # contract is to emit lines to stdout — we never need to propagate
        # state back to the function.
        [[ "$micro" == "0" ]] && continue
        printf '    ["%s"]="%s"\n' "$model" "$(_micro_usd_to_per_1k "$micro")"
    done

    # Aliases: inherit pricing from canonical target
    yq eval -o=json '.aliases // {}' "$CONFIG_FILE" | jq -r '
        to_entries[]
        | select((.value | split(":")[0]) != "claude-code")
        | select(.value | test("^[^:]+:"))
        | "\(.key)\t\(.value)"
    ' | while IFS=$'\t' read -r alias provider_model; do
        provider="${provider_model%%:*}"
        model="${provider_model#*:}"
        micro=$(yq eval ".providers[\"$provider\"].models[\"$model\"].pricing.$field // 0" "$CONFIG_FILE")
        [[ "$micro" == "0" || "$micro" == "null" ]] && continue
        printf '    ["%s"]="%s"\n' "$alias" "$(_micro_usd_to_per_1k "$micro")"
    done

    # Backward-compat aliases: inherit from canonical target
    yq eval -o=json '.backward_compat_aliases // {}' "$CONFIG_FILE" | jq -r '
        to_entries[] | "\(.key)\t\(.value)"
    ' | while IFS=$'\t' read -r alias provider_model; do
        provider="${provider_model%%:*}"
        model="${provider_model#*:}"
        micro=$(yq eval ".providers[\"$provider\"].models[\"$model\"].pricing.$field // 0" "$CONFIG_FILE")
        [[ "$micro" == "0" || "$micro" == "null" ]] && continue
        printf '    ["%s"]="%s"\n' "$alias" "$(_micro_usd_to_per_1k "$micro")"
    done
}

if [[ "$CHECK" == "true" ]]; then
    tmpfile=$(mktemp)
    trap 'rm -f "$tmpfile"' EXIT
    generate > "$tmpfile"
    if ! diff -q "$OUTPUT_FILE" "$tmpfile" >/dev/null 2>&1; then
        echo "Drift detected between $OUTPUT_FILE and current YAML" >&2
        echo "Run: bash .claude/scripts/gen-adapter-maps.sh" >&2
        exit 3
    fi
    echo "OK: $OUTPUT_FILE matches YAML"
    exit 0
fi

if [[ "$DRY_RUN" == "true" ]]; then
    generate
    exit 0
fi

tmpfile=$(mktemp)
trap 'rm -f "$tmpfile"' EXIT
generate > "$tmpfile"
mv "$tmpfile" "$OUTPUT_FILE"
echo "Wrote: $OUTPUT_FILE"
