#!/bin/bash
# =============================================================================
# generate-changelog.sh - Cycle Changelog Generator
# =============================================================================
# Sprint 9, Task 9.1-9.3: Generate changelog for development cycle
#
# Usage:
#   ./generate-changelog.sh [options]
#
# Options:
#   --cycle N        Cycle number (default: current)
#   --output FORMAT  Output format: markdown (default), json
#   --file PATH      Write to file instead of stdout
#   --help           Show this help
# =============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
LEDGER_FILE="${PROJECT_ROOT}/grimoires/loa/ledger.json"
PATTERNS_FILE="${PROJECT_ROOT}/grimoires/loa/a2a/compound/patterns.json"
SKILLS_DIR="${PROJECT_ROOT}/grimoires/loa/skills"

CYCLE_NUM=""
OUTPUT_FORMAT="markdown"
OUTPUT_FILE=""

usage() {
  sed -n '/^# Usage:/,/^# =====/p' "$0" | grep -v "^# =====" | sed 's/^# //'
  exit 0
}

parse_args() {
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --cycle) CYCLE_NUM="$2"; shift 2 ;;
      --output) OUTPUT_FORMAT="$2"; shift 2 ;;
      --file) OUTPUT_FILE="$2"; shift 2 ;;
      --help|-h) usage ;;
      *) shift ;;
    esac
  done
}

get_cycle_info() {
  if [[ ! -f "$LEDGER_FILE" ]]; then
    echo '{"number": 1, "start_date": "unknown", "end_date": "unknown"}'
    return
  fi
  
  if [[ -n "$CYCLE_NUM" ]]; then
    jq --arg n "$CYCLE_NUM" '.cycles[] | select(.number == ($n | tonumber))' "$LEDGER_FILE" 2>/dev/null || echo "{}"
  else
    jq '.cycles | last // {}' "$LEDGER_FILE" 2>/dev/null || echo "{}"
  fi
}

get_patterns_count() {
  if [[ -f "$PATTERNS_FILE" ]]; then
    jq '.patterns | length' "$PATTERNS_FILE" 2>/dev/null || echo "0"
  else
    echo "0"
  fi
}

get_skills_count() {
  if [[ -d "$SKILLS_DIR" ]]; then
    find "$SKILLS_DIR" -name "SKILL.md" 2>/dev/null | wc -l | tr -d ' '
  else
    echo "0"
  fi
}

generate_markdown() {
  local cycle_info
  cycle_info=$(get_cycle_info)
  
  local cycle_num start_date end_date
  cycle_num=$(echo "$cycle_info" | jq -r '.number // "N/A"')
  start_date=$(echo "$cycle_info" | jq -r '.start_date // "unknown"')
  end_date=$(echo "$cycle_info" | jq -r '.end_date // "unknown"')
  
  local patterns_count skills_count
  patterns_count=$(get_patterns_count)
  skills_count=$(get_skills_count)
  
  cat << EOF
# Changelog - Cycle $cycle_num

**Period:** $start_date to $end_date
**Generated:** $(date -u +%Y-%m-%dT%H:%M:%SZ)

## Summary

| Metric | Value |
|--------|-------|
| Patterns Detected | $patterns_count |
| Skills Extracted | $skills_count |

## Patterns Detected

EOF

  if [[ -f "$PATTERNS_FILE" && "$patterns_count" -gt 0 ]]; then
    jq -r '.patterns[] | "- **\(.signature)** (\(.type)) - Confidence: \((.confidence * 100) | floor)%"' "$PATTERNS_FILE" 2>/dev/null || echo "*(No patterns)*"
  else
    echo "*(No patterns detected)*"
  fi

  cat << EOF

## Skills Extracted

EOF

  if [[ -d "$SKILLS_DIR" && "$skills_count" -gt 0 ]]; then
    find "$SKILLS_DIR" -name "SKILL.md" -exec dirname {} \; 2>/dev/null | xargs -I {} basename {} | while read -r skill; do
      echo "- $skill"
    done
  else
    echo "*(No skills extracted)*"
  fi

  cat << EOF

---
*Generated by Compound Learning System*
EOF
}

generate_json() {
  local cycle_info
  cycle_info=$(get_cycle_info)
  
  local patterns_count skills_count
  patterns_count=$(get_patterns_count)
  skills_count=$(get_skills_count)
  
  jq -n \
    --argjson cycle "$cycle_info" \
    --argjson patterns "$patterns_count" \
    --argjson skills "$skills_count" \
    --arg generated "$(date -u +%Y-%m-%dT%H:%M:%SZ)" \
    '{
      cycle: $cycle,
      generated: $generated,
      summary: {
        patterns_detected: $patterns,
        skills_extracted: $skills
      }
    }'
}

main() {
  parse_args "$@"
  
  local output
  case "$OUTPUT_FORMAT" in
    json) output=$(generate_json) ;;
    *) output=$(generate_markdown) ;;
  esac
  
  if [[ -n "$OUTPUT_FILE" ]]; then
    mkdir -p "$(dirname "$OUTPUT_FILE")"
    echo "$output" > "$OUTPUT_FILE"
    echo "[INFO] Written to $OUTPUT_FILE"
  else
    echo "$output"
  fi
}

main "$@"
