#!/usr/bin/env tsx
/**
 * S0-T0 — Harness vendoring preflight
 *
 * Per SDD §2.5 (added r1 post-orchestrator-flatline SKP-002 severity-760).
 * Resolves the purupuru architecture harness path with a 3-tier fallback,
 * asserts the canonical file inventory exists, computes SHA-256 per file,
 * and writes `lib/purupuru/schemas/PROVENANCE.md`.
 *
 * Exit codes:
 *   0  — preflight passed; PROVENANCE.md written
 *   1  — hash mismatch against existing PROVENANCE.md (operator must reconcile)
 *  78  — EX_CONFIG: harness path not resolvable; operator action required
 *
 * Resolution order (highest precedence first):
 *   1. LOA_PURUPURU_HARNESS_PATH env var
 *   2. ~/.loa.config.yaml :: purupuru.harness_path  (not implemented this cycle)
 *   3. ~/Downloads/purupuru_architecture_harness/   (default machine-local)
 */

import { createHash } from "node:crypto";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { join, resolve } from "node:path";

const REPO_ROOT = resolve(__dirname, "..");
const PROVENANCE_PATH = join(REPO_ROOT, "lib/purupuru/schemas/PROVENANCE.md");

interface ExpectedFile {
  relative: string;
  category: "schema" | "yaml" | "contract" | "readme";
}

const EXPECTED_FILES: ExpectedFile[] = [
  // 8 schemas
  { relative: "schemas/element.schema.json", category: "schema" },
  { relative: "schemas/card.schema.json", category: "schema" },
  { relative: "schemas/zone.schema.json", category: "schema" },
  { relative: "schemas/event.schema.json", category: "schema" },
  { relative: "schemas/presentation_sequence.schema.json", category: "schema" },
  { relative: "schemas/ui_screen.schema.json", category: "schema" },
  { relative: "schemas/content_pack_manifest.schema.json", category: "schema" },
  { relative: "schemas/telemetry_event.schema.json", category: "schema" },
  // 8 YAMLs
  { relative: "examples/element.wood.yaml", category: "yaml" },
  { relative: "examples/card.wood_awakening.yaml", category: "yaml" },
  { relative: "examples/zone.wood_grove.yaml", category: "yaml" },
  { relative: "examples/event.wood_spring_seedling.yaml", category: "yaml" },
  { relative: "examples/sequence.wood_activation.yaml", category: "yaml" },
  { relative: "examples/ui.world_map_screen.yaml", category: "yaml" },
  { relative: "examples/pack.core_wood_demo.yaml", category: "yaml" },
  { relative: "examples/telemetry.card_activation_clarity.yaml", category: "yaml" },
  // 2 contracts + README
  { relative: "contracts/purupuru.contracts.ts", category: "contract" },
  { relative: "contracts/validation_rules.md", category: "contract" },
  { relative: "README.md", category: "readme" },
];

function resolveHarnessPath(): string | null {
  const envPath = process.env.LOA_PURUPURU_HARNESS_PATH;
  if (envPath) {
    if (existsSync(envPath)) return envPath;
    console.error(`[s0-preflight] LOA_PURUPURU_HARNESS_PATH set to ${envPath} but path does not exist.`);
    return null;
  }
  const defaultPath = join(homedir(), "Downloads/purupuru_architecture_harness");
  if (existsSync(defaultPath)) return defaultPath;
  return null;
}

function sha256(filePath: string): string {
  const bytes = readFileSync(filePath);
  return createHash("sha256").update(bytes).digest("hex");
}

function extractHarnessVersion(readmePath: string): string {
  const content = readFileSync(readmePath, "utf8");
  // README line 3: "**Version:** 0.1 draft"
  const match = content.match(/\*\*Version:\*\*\s*(.+)/);
  return match ? match[1].trim() : "unknown";
}

interface ProvenanceEntry {
  category: string;
  source_path: string;
  sha256: string;
}

function buildProvenanceMarkdown(
  harnessPath: string,
  version: string,
  entries: ProvenanceEntry[],
): string {
  const ts = new Date().toISOString();
  const lines: string[] = [
    "# Purupuru Architecture Harness — Provenance",
    "",
    `> Generated by \`scripts/s0-preflight-harness.ts\` (cycle-1 S0-T0).`,
    `> Per SDD §2.5 harness vendoring preflight.`,
    "",
    `**Source path:** \`${harnessPath}\``,
    `**Harness version:** \`${version}\``,
    `**Vendoring timestamp:** ${ts}`,
    `**Total entries:** ${entries.length}`,
    "",
    "## File hashes (SHA-256)",
    "",
  ];
  for (const e of entries) {
    lines.push(`- ${e.category} · \`${e.source_path}\` · sha256: \`${e.sha256}\``);
  }
  lines.push("");
  lines.push("## Verification");
  lines.push("");
  lines.push("Subsequent `pnpm s0:preflight` invocations recompute hashes and assert match.");
  lines.push("Hash mismatch → exit 1 → operator reconciles (likely upstream harness revision).");
  lines.push("");
  return lines.join("\n");
}

function main(): number {
  const harnessPath = resolveHarnessPath();
  if (!harnessPath) {
    console.error("");
    console.error("[s0-preflight] harness source not found.");
    console.error("");
    console.error("Resolution options:");
    console.error("  1. Set LOA_PURUPURU_HARNESS_PATH env var to harness directory");
    console.error("  2. Place harness at ~/Downloads/purupuru_architecture_harness/");
    console.error("");
    console.error("See grimoires/loa/cycles/purupuru-cycle-1-wood-vertical-2026-05-13/sdd.md §2.5");
    return 78; // EX_CONFIG
  }

  console.log(`[s0-preflight] Resolved harness path: ${harnessPath}`);

  // Assert file inventory
  const missing: string[] = [];
  for (const f of EXPECTED_FILES) {
    if (!existsSync(join(harnessPath, f.relative))) missing.push(f.relative);
  }
  if (missing.length > 0) {
    console.error(`[s0-preflight] Missing ${missing.length} file(s):`);
    for (const m of missing) console.error(`  - ${m}`);
    return 78;
  }

  console.log(`[s0-preflight] All ${EXPECTED_FILES.length} files present.`);

  // Compute hashes
  const entries: ProvenanceEntry[] = [];
  for (const f of EXPECTED_FILES) {
    const fullPath = join(harnessPath, f.relative);
    entries.push({
      category: f.category,
      source_path: f.relative,
      sha256: sha256(fullPath),
    });
  }

  // Extract harness version from README
  const version = extractHarnessVersion(join(harnessPath, "README.md"));
  console.log(`[s0-preflight] Harness version: ${version}`);

  // If PROVENANCE.md exists, compare hashes
  if (existsSync(PROVENANCE_PATH)) {
    const existing = readFileSync(PROVENANCE_PATH, "utf8");
    const existingHashes = new Set(
      [...existing.matchAll(/sha256: `([a-f0-9]{64})`/g)].map((m) => m[1]),
    );
    const newHashes = new Set(entries.map((e) => e.sha256));
    const matches = [...newHashes].every((h) => existingHashes.has(h));
    if (!matches) {
      console.error(`[s0-preflight] Hash mismatch against existing PROVENANCE.md.`);
      console.error(`[s0-preflight] Existing: ${existingHashes.size} hashes`);
      console.error(`[s0-preflight] Current:  ${newHashes.size} hashes`);
      console.error(`[s0-preflight] Operator must reconcile (likely upstream harness revision).`);
      return 1;
    }
    console.log(`[s0-preflight] Hashes match existing PROVENANCE.md (no upstream drift).`);
  }

  // Write PROVENANCE.md
  const provenanceDir = join(REPO_ROOT, "lib/purupuru/schemas");
  if (!existsSync(provenanceDir)) mkdirSync(provenanceDir, { recursive: true });
  const markdown = buildProvenanceMarkdown(harnessPath, version, entries);
  writeFileSync(PROVENANCE_PATH, markdown);
  console.log(`[s0-preflight] Wrote ${PROVENANCE_PATH} (${entries.length} entries).`);

  console.log(`[s0-preflight] ✓ Preflight passed.`);
  return 0;
}

process.exit(main());
