/**
 * Daily meta tests.
 */

import { describe, expect, it } from "vitest";
import { getDailyMeta, getDailyMetaOffset, getDailyShift } from "./daily-meta";

describe("getDailyMeta", () => {
  it("is deterministic for the same date", () => {
    const d = new Date("2026-05-12T12:00:00Z");
    const a = getDailyMeta(d);
    const b = getDailyMeta(d);
    expect(a.dateKey).toBe(b.dateKey);
    expect(a.weather).toBe(b.weather);
    expect(a.opponentElement).toBe(b.opponentElement);
    expect(a.condition.id).toBe(b.condition.id);
  });

  it("changes the weather across the 5-day cycle", () => {
    const elements = new Set<string>();
    for (let i = 0; i < 5; i++) {
      const d = new Date(2026, 4, 12 + i);
      elements.add(getDailyMeta(d).weather);
    }
    expect(elements.size).toBe(5);
  });

  it("opponent element differs from weather most days (phase offset)", () => {
    let sameCount = 0;
    for (let i = 0; i < 10; i++) {
      const d = new Date(2026, 4, 12 + i);
      const meta = getDailyMeta(d);
      if (meta.weather === meta.opponentElement) sameCount++;
    }
    // With a +2 phase offset on a 5-cycle, weather and opponent should never coincide.
    expect(sameCount).toBe(0);
  });

  it("favoredElement is the Shēng-generated by weather", () => {
    const d = new Date(2026, 4, 12);
    const meta = getDailyMeta(d);
    const SHENG: Record<string, string> = {
      wood: "fire",
      fire: "earth",
      earth: "metal",
      metal: "water",
      water: "wood",
    };
    expect(meta.favoredElement).toBe(SHENG[meta.weather]);
  });

  it("label is a non-empty human-readable phrase", () => {
    const meta = getDailyMeta(new Date());
    expect(meta.label.length).toBeGreaterThan(10);
    expect(meta.label).toMatch(/weather/);
    expect(meta.label).toMatch(/challenge/);
  });
});

describe("getDailyMetaOffset", () => {
  it("offset 0 equals today", () => {
    const d = new Date(2026, 4, 12);
    expect(getDailyMetaOffset(0, d).weather).toBe(getDailyMeta(d).weather);
  });

  it("offset 1 differs from today (weather rotates daily)", () => {
    const d = new Date(2026, 4, 12);
    expect(getDailyMetaOffset(1, d).weather).not.toBe(getDailyMeta(d).weather);
  });

  it("offset 5 returns to today (cycle wraps)", () => {
    const d = new Date(2026, 4, 12);
    expect(getDailyMetaOffset(5, d).weather).toBe(getDailyMeta(d).weather);
  });
});

describe("getDailyShift", () => {
  it("at least one of weather/opponent/condition changes every day", () => {
    const d = new Date(2026, 4, 12);
    const shift = getDailyShift(d);
    expect(shift.any).toBe(true);
  });

  it("weather changes every day (5-cycle without runs)", () => {
    for (let i = 0; i < 10; i++) {
      const d = new Date(2026, 4, 12 + i);
      expect(getDailyShift(d).weatherChanged, d.toDateString()).toBe(true);
    }
  });
});
