#!/usr/bin/env bats
bats_require_minimum_version 1.5.0
# =============================================================================
# overlay-source-helper.bats — cycle-099 Sprint 2C (T2.5)
#
# Unit tests for `.claude/scripts/lib/overlay-source-helper.sh`. Each helper
# function exercised in isolation with a fixture-controlled merged file.
# =============================================================================

setup() {
  REPO_ROOT="$(cd "$BATS_TEST_DIRNAME/../.." && pwd)"
  HELPER="$REPO_ROOT/.claude/scripts/lib/overlay-source-helper.sh"
  WORK="$(mktemp -d)"
  MERGED="$WORK/merged-model-aliases.sh"
  LOCKFILE="$MERGED.lock"
  # Override the helper's default paths via env vars so tests don't touch
  # the real .run/ directory. Per CYP-F1 dual-review fix, the override now
  # requires a 3-leg gate (LOA_OVERLAY_HELPER_TEST_MODE=1 + the path env
  # var + BATS_VERSION/PYTEST_CURRENT_TEST). bats sets BATS_VERSION
  # automatically.
  export LOA_OVERLAY_HELPER_TEST_MODE=1
  export LOA_OVERLAY_MERGED="$MERGED"
  export LOA_OVERLAY_LOCKFILE="$LOCKFILE"
  # Drop any stale overlay state in the parent shell. bats runs each @test
  # in a subshell so this is mostly defensive.
  unset LOA_OVERLAY_VERSION_AT_LOAD
  unset LOA_OVERLAY_FINGERPRINT
  # Clear arrays if they linger from a prior source
  unset LOA_MODEL_PROVIDERS LOA_MODEL_IDS LOA_MODEL_ENDPOINT_FAMILIES \
        LOA_MODEL_COST_INPUT_PER_MTOK LOA_MODEL_COST_OUTPUT_PER_MTOK
}

teardown() {
  rm -rf "$WORK"
}

# Helper: write a sample merged file fixture
_fixture_merged() {
  local version="${1:-1}"
  local sha="${2:-$(printf 'a%.0s' {1..64})}"
  cat > "$MERGED" <<EOF
# Generated by .claude/scripts/lib/model-overlay-hook.py at 2026-05-06T00:00:00Z
# version=$version
# source-sha256=$sha
# holder-pid=12345
# DO NOT EDIT — regenerate via \`loa-overlay-hook regen\`

declare -gA LOA_MODEL_PROVIDERS=(
  [opus]=anthropic
  [reviewer]=openai
  [my-extra]=openai
)

declare -gA LOA_MODEL_IDS=(
  [opus]=claude-opus-4-7
  [reviewer]=gpt-5.5
  [my-extra]=gpt-5.7-pro
)

declare -gA LOA_MODEL_ENDPOINT_FAMILIES=(
  [opus]=messages
  [reviewer]=responses
  [my-extra]=responses
)

declare -gA LOA_MODEL_COST_INPUT_PER_MTOK=(
  [opus]=5000000
  [reviewer]=5000000
  [my-extra]=40000000
)

declare -gA LOA_MODEL_COST_OUTPUT_PER_MTOK=(
  [opus]=25000000
  [reviewer]=30000000
  [my-extra]=200000000
)

LOA_OVERLAY_FINGERPRINT=abc123def456
EOF
  # Create the lockfile (empty) so the shared-flock path can be exercised
  : > "$LOCKFILE"
}

# -----------------------------------------------------------------------------
# A — loa_overlay_read_version
# -----------------------------------------------------------------------------

@test "A1: loa_overlay_read_version returns version from header" {
  _fixture_merged 42
  source "$HELPER"
  run loa_overlay_read_version
  [ "$status" -eq 0 ]
  [ "$output" = "42" ]
}

@test "A2: loa_overlay_read_version returns 1 on missing file" {
  source "$HELPER"
  run loa_overlay_read_version
  [ "$status" -eq 1 ]
  [ -z "$output" ]
}

@test "A3: loa_overlay_read_version returns 1 on header-less file" {
  cat > "$MERGED" <<EOF
# no version header here
declare -gA LOA_MODEL_PROVIDERS=()
EOF
  source "$HELPER"
  run loa_overlay_read_version
  [ "$status" -eq 1 ]
}

@test "A4: loa_overlay_read_version handles trailing whitespace" {
  cat > "$MERGED" <<EOF
# Generated...
# version=99
EOF
  source "$HELPER"
  run loa_overlay_read_version
  [ "$status" -eq 0 ]
  [ "$output" = "99" ]
}

# -----------------------------------------------------------------------------
# B — loa_overlay_read_source_sha
# -----------------------------------------------------------------------------

@test "B1: loa_overlay_read_source_sha returns hex digest" {
  local sha="abc123def456abc123def456abc123def456abc123def456abc123def456abc1"
  _fixture_merged 1 "$sha"
  source "$HELPER"
  run loa_overlay_read_source_sha
  [ "$status" -eq 0 ]
  [ "$output" = "$sha" ]
}

@test "B2: loa_overlay_read_source_sha rejects non-64-char hex" {
  cat > "$MERGED" <<EOF
# version=1
# source-sha256=tooshort
EOF
  source "$HELPER"
  run loa_overlay_read_source_sha
  [ "$status" -eq 1 ]
}

# -----------------------------------------------------------------------------
# C — loa_overlay_init
# -----------------------------------------------------------------------------

@test "C1: loa_overlay_init populates the 5 LOA_MODEL_* arrays" {
  _fixture_merged 1
  source "$HELPER"
  run loa_overlay_init
  [ "$status" -eq 0 ]
  # Re-source in the test shell to pick up the populated arrays. (run
  # invokes a subshell — populated arrays don't propagate back.)
  source "$HELPER"
  loa_overlay_init
  [ "${LOA_MODEL_PROVIDERS[opus]}" = "anthropic" ]
  [ "${LOA_MODEL_IDS[opus]}" = "claude-opus-4-7" ]
  [ "${LOA_MODEL_ENDPOINT_FAMILIES[opus]}" = "messages" ]
  [ "${LOA_MODEL_COST_INPUT_PER_MTOK[opus]}" = "5000000" ]
  [ "${LOA_MODEL_COST_OUTPUT_PER_MTOK[opus]}" = "25000000" ]
}

@test "C2: loa_overlay_init sets LOA_OVERLAY_VERSION_AT_LOAD" {
  _fixture_merged 7
  source "$HELPER"
  loa_overlay_init
  [ "$LOA_OVERLAY_VERSION_AT_LOAD" = "7" ]
}

@test "C3: loa_overlay_init sets LOA_OVERLAY_FINGERPRINT" {
  _fixture_merged 1
  source "$HELPER"
  loa_overlay_init
  [ "$LOA_OVERLAY_FINGERPRINT" = "abc123def456" ]
}

@test "C4: loa_overlay_init returns 1 when target absent AND regen fails (BB-iter-2 F4 + iter-3 F1)" {
  # Per BB iter-2 F4 + iter-3 F1: the test must be deterministic AND the
  # failure surface must be unambiguous.
  #
  # We use a parent directory with mode 0000 (no perms) — the hook's
  # _atomic_write_text calls target_dir.mkdir(parents=True, exist_ok=True),
  # which succeeds (parent exists), but then os.open() of the tempfile
  # under it fails with EACCES. The hook catches OSError, emits
  # [MERGED-ALIASES-WRITE-FAILED], exits 78. The helper sees a non-zero
  # rc from the hook + still-missing merged file, returns 1.
  #
  # This is unambiguous: the only failure path is "parent dir unwritable".
  # No platform-dependent ENOTDIR semantics; no behavior dependence on
  # whether the helper's mkdir+open pair is atomic.
  local readonly_dir="$WORK/readonly-parent"
  mkdir -p "$readonly_dir"
  chmod 0500 "$readonly_dir"   # readable + executable, but NOT writable
  local target="$readonly_dir/will-never-be-created.sh"
  local lockfile="$target.lock"
  export LOA_OVERLAY_MERGED="$target"
  export LOA_OVERLAY_LOCKFILE="$lockfile"
  source "$HELPER"
  run loa_overlay_init
  [ "$status" -eq 1 ]
  # Cleanup: restore writable permissions so teardown can rmdir
  chmod 0700 "$readonly_dir"
}

@test "C5: loa_overlay_init refuses to source content failing bash syntax check" {
  # Construct a file with a header but invalid bash body
  cat > "$MERGED" <<EOF
# version=1
this is not valid bash {{{
EOF
  : > "$LOCKFILE"
  source "$HELPER"
  run loa_overlay_init
  [ "$status" -eq 1 ]
}

# -----------------------------------------------------------------------------
# D — loa_overlay_resolve_provider_id
# -----------------------------------------------------------------------------

@test "D1: loa_overlay_resolve_provider_id returns provider:api_id format" {
  _fixture_merged 1
  source "$HELPER"
  loa_overlay_init
  run loa_overlay_resolve_provider_id "opus"
  [ "$status" -eq 0 ]
  [ "$output" = "anthropic:claude-opus-4-7" ]
}

@test "D2: loa_overlay_resolve_provider_id returns 1 on miss" {
  _fixture_merged 1
  source "$HELPER"
  loa_overlay_init
  run loa_overlay_resolve_provider_id "no-such-alias"
  [ "$status" -eq 1 ]
  [ -z "$output" ]
}

@test "D3: loa_overlay_resolve_provider_id returns 1 when arrays not populated" {
  source "$HELPER"
  # Don't call loa_overlay_init — arrays should be unset
  run loa_overlay_resolve_provider_id "opus"
  [ "$status" -eq 1 ]
}

@test "D4: loa_overlay_resolve_provider_id returns operator-added alias from extras" {
  _fixture_merged 1
  source "$HELPER"
  loa_overlay_init
  run loa_overlay_resolve_provider_id "my-extra"
  [ "$status" -eq 0 ]
  [ "$output" = "openai:gpt-5.7-pro" ]
}

@test "D5: loa_overlay_resolve_provider_id returns 1 on empty alias" {
  _fixture_merged 1
  source "$HELPER"
  loa_overlay_init
  run loa_overlay_resolve_provider_id ""
  [ "$status" -eq 1 ]
}

# -----------------------------------------------------------------------------
# E — loa_overlay_resolve_alias
# -----------------------------------------------------------------------------

@test "E1: loa_overlay_resolve_alias returns api_id only (no provider prefix)" {
  _fixture_merged 1
  source "$HELPER"
  loa_overlay_init
  run loa_overlay_resolve_alias "reviewer"
  [ "$status" -eq 0 ]
  [ "$output" = "gpt-5.5" ]
}

@test "E2: loa_overlay_resolve_alias returns 1 on miss" {
  _fixture_merged 1
  source "$HELPER"
  loa_overlay_init
  run loa_overlay_resolve_alias "no-such-alias"
  [ "$status" -eq 1 ]
}

# -----------------------------------------------------------------------------
# F — loa_overlay_resolve_endpoint_family
# -----------------------------------------------------------------------------

@test "F1: loa_overlay_resolve_endpoint_family returns family string" {
  _fixture_merged 1
  source "$HELPER"
  loa_overlay_init
  run loa_overlay_resolve_endpoint_family "opus"
  [ "$status" -eq 0 ]
  [ "$output" = "messages" ]

  run loa_overlay_resolve_endpoint_family "reviewer"
  [ "$status" -eq 0 ]
  [ "$output" = "responses" ]
}

@test "F2: loa_overlay_resolve_endpoint_family returns 1 on miss" {
  _fixture_merged 1
  source "$HELPER"
  loa_overlay_init
  run loa_overlay_resolve_endpoint_family "unknown"
  [ "$status" -eq 1 ]
}

# -----------------------------------------------------------------------------
# G — loa_overlay_refresh_if_stale
# -----------------------------------------------------------------------------

@test "G1: loa_overlay_refresh_if_stale is a no-op when version unchanged" {
  _fixture_merged 5
  source "$HELPER"
  loa_overlay_init
  [ "$LOA_OVERLAY_VERSION_AT_LOAD" = "5" ]
  # Do not modify the file; refresh should be a no-op
  run loa_overlay_refresh_if_stale
  [ "$status" -eq 0 ]
  [ "$LOA_OVERLAY_VERSION_AT_LOAD" = "5" ]
}

@test "G2: loa_overlay_refresh_if_stale re-sources when version bumps" {
  _fixture_merged 5
  source "$HELPER"
  loa_overlay_init
  [ "$LOA_OVERLAY_VERSION_AT_LOAD" = "5" ]
  # Bump the file's version (simulating cross-process regen)
  _fixture_merged 6
  loa_overlay_refresh_if_stale
  [ "$LOA_OVERLAY_VERSION_AT_LOAD" = "6" ]
}

@test "G3: loa_overlay_refresh_if_stale returns 0 when not initialized" {
  source "$HELPER"
  # Don't call loa_overlay_init
  run loa_overlay_refresh_if_stale
  [ "$status" -eq 0 ]
}

@test "G4: loa_overlay_refresh_if_stale picks up new operator alias on bump" {
  # Initial fixture has 'my-extra'. Refresh with a different alias.
  _fixture_merged 1
  source "$HELPER"
  loa_overlay_init
  run loa_overlay_resolve_provider_id "my-extra"
  [ "$status" -eq 0 ]

  # Rewrite fixture with a NEW operator alias 'never-before-seen' (and bump version)
  cat > "$MERGED" <<EOF
# Generated...
# version=2
# source-sha256=$(printf 'b%.0s' {1..64})
# holder-pid=99
# DO NOT EDIT

declare -gA LOA_MODEL_PROVIDERS=(
  [never-before-seen]=anthropic
)

declare -gA LOA_MODEL_IDS=(
  [never-before-seen]=claude-3-haiku
)

declare -gA LOA_MODEL_ENDPOINT_FAMILIES=(
  [never-before-seen]=messages
)

declare -gA LOA_MODEL_COST_INPUT_PER_MTOK=(
  [never-before-seen]=1
)

declare -gA LOA_MODEL_COST_OUTPUT_PER_MTOK=(
  [never-before-seen]=2
)

LOA_OVERLAY_FINGERPRINT=def456abcdef
EOF
  loa_overlay_refresh_if_stale
  [ "$LOA_OVERLAY_VERSION_AT_LOAD" = "2" ]
  run loa_overlay_resolve_provider_id "never-before-seen"
  [ "$status" -eq 0 ]
  [ "$output" = "anthropic:claude-3-haiku" ]
}

# -----------------------------------------------------------------------------
# H — Defense: bash syntax check rejects hostile content
# -----------------------------------------------------------------------------

@test "H1: content-shape gate rejects command-substitution probe (CYP-F2)" {
  # Iter-1 dual-review fix: the new _loa_overlay_validate_shape gate
  # rejects shapes the writer never emits — including command-substitution,
  # backticks, semicolons, pipes, and any non-allowlist chars in keys/values.
  # This is defense-in-depth on top of the writer's shell-escape gate.
  cat > "$MERGED" <<'EOF'
# version=1
# source-sha256=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
declare -gA LOA_MODEL_PROVIDERS=(
  [pwn]=$(touch /tmp/loa-test-pwned-XYZZY)
)
EOF
  : > "$LOCKFILE"
  source "$HELPER"
  run loa_overlay_init
  # Refused: shape gate rejects `$(...)` content
  [ "$status" -eq 1 ]
  # Pwn marker NOT created (the gate refuses BEFORE source)
  [ ! -f "/tmp/loa-test-pwned-XYZZY" ]
}

@test "H2: source refuses syntactically-invalid content (bash -n catches)" {
  cat > "$MERGED" <<'EOF'
# version=1
this is { bonkers (((
EOF
  : > "$LOCKFILE"
  source "$HELPER"
  run loa_overlay_init
  [ "$status" -eq 1 ]
}

@test "H3: content-shape gate rejects backtick command-substitution" {
  cat > "$MERGED" <<'EOF'
# version=1
# source-sha256=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
declare -gA LOA_MODEL_PROVIDERS=(
  [pwn]=`whoami`
)
EOF
  : > "$LOCKFILE"
  source "$HELPER"
  run loa_overlay_init
  [ "$status" -eq 1 ]
}

@test "H4: content-shape gate rejects semicolon-injection in value" {
  cat > "$MERGED" <<'EOF'
# version=1
# source-sha256=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
declare -gA LOA_MODEL_PROVIDERS=(
  [pwn]=safe;rm
)
EOF
  : > "$LOCKFILE"
  source "$HELPER"
  run loa_overlay_init
  [ "$status" -eq 1 ]
}

@test "H5: content-shape gate rejects extra trailing line outside arrays" {
  cat > "$MERGED" <<'EOF'
# version=1
# source-sha256=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
declare -gA LOA_MODEL_PROVIDERS=()
declare -gA LOA_MODEL_IDS=()
declare -gA LOA_MODEL_ENDPOINT_FAMILIES=()
declare -gA LOA_MODEL_COST_INPUT_PER_MTOK=()
declare -gA LOA_MODEL_COST_OUTPUT_PER_MTOK=()
LOA_OVERLAY_FINGERPRINT=aaaaaaaaaaaa
extra-attacker-line=evil
EOF
  : > "$LOCKFILE"
  source "$HELPER"
  run loa_overlay_init
  [ "$status" -eq 1 ]
}

# -----------------------------------------------------------------------------
# I — Iter-1 dual-review fix regression pins
# -----------------------------------------------------------------------------

@test "I1 (CYP-F1): partial gate (TEST_MODE=1 only) does NOT honor LOA_OVERLAY_MERGED override" {
  # When LOA_OVERLAY_HELPER_TEST_MODE=1 is set BUT BATS_VERSION /
  # PYTEST_CURRENT_TEST aren't, the override must be IGNORED and the
  # helper must resolve to the DEFAULT repo path. Per BB iter-2 F3:
  # we explicitly assert the default path shape (ends in
  # .run/merged-model-aliases.sh) rather than just != $MERGED, so a
  # bug that leaves _OVERLAY_HELPER_MERGED unset would fail loudly.
  _fixture_merged 1
  run env -i \
    LOA_OVERLAY_HELPER_TEST_MODE=1 \
    LOA_OVERLAY_MERGED="$MERGED" \
    PATH="/usr/bin:/bin" \
    HOME="$HOME" \
    bash -c '
      set -u
      source '"$HELPER"'
      # The override must NOT apply. We assert the resolved path is
      # the default (ends in .run/merged-model-aliases.sh) AND that it
      # is set (set -u catches unset).
      if [[ "$_OVERLAY_HELPER_MERGED" != *"/.run/merged-model-aliases.sh" ]]; then
          echo "EXPECTED default path, got: $_OVERLAY_HELPER_MERGED" >&2
          exit 2
      fi
      if [[ "$_OVERLAY_HELPER_MERGED" == "'"$MERGED"'" ]]; then
          echo "OVERRIDE LEAKED through gate" >&2
          exit 3
      fi
    '
  [ "$status" -eq 0 ]
}

@test "I2 (CYP-F1): full 3-leg gate (TEST_MODE + path + BATS_VERSION) honors override" {
  _fixture_merged 1
  run env -i \
    LOA_OVERLAY_HELPER_TEST_MODE=1 \
    LOA_OVERLAY_MERGED="$MERGED" \
    BATS_VERSION="1.13.0" \
    PATH="/usr/bin:/bin" \
    HOME="$HOME" \
    bash -c '
      source '"$HELPER"'
      [[ "$_OVERLAY_HELPER_MERGED" == "'"$MERGED"'" ]] || { echo "GATE FAILED" >&2; exit 2; }
    '
  [ "$status" -eq 0 ]
}

@test "I3 (CYP-F4): symlink at merged path is refused" {
  _fixture_merged 1
  # Construct a decoy file and replace MERGED with a symlink to it
  local decoy="$WORK/decoy.sh"
  cp "$MERGED" "$decoy"
  rm "$MERGED"
  ln -s "$decoy" "$MERGED"
  source "$HELPER"
  run loa_overlay_init
  [ "$status" -eq 1 ]
}

@test "I4 (CYP-F6): pre-poisoned LOA_MODEL_* arrays are cleared before source" {
  # Pre-populate arrays as if an attacker exported them
  declare -gA LOA_MODEL_PROVIDERS=( [opus]=evil-provider [poisoned-only]=evil )
  declare -gA LOA_MODEL_IDS=( [opus]=https://evil.com [poisoned-only]=hostile )

  _fixture_merged 1
  source "$HELPER"
  loa_overlay_init

  # After init, the merged file's clean values overwrite the poisoned ones
  [ "${LOA_MODEL_PROVIDERS[opus]}" = "anthropic" ]
  [ "${LOA_MODEL_IDS[opus]}" = "claude-opus-4-7" ]
  # And the poisoned-only key (not in the merged file) is gone
  [ -z "${LOA_MODEL_PROVIDERS[poisoned-only]:-}" ]
  [ -z "${LOA_MODEL_IDS[poisoned-only]:-}" ]
}

@test "I5 (CYP-F7): _OVERLAY_HELPER_HOOK is readonly after source" {
  source "$HELPER"
  # Attempt to reassign should fail. Use `||` to capture the failure
  # rather than letting set -e abort the test.
  ( _OVERLAY_HELPER_HOOK="/tmp/evil.py" 2>&1 ) && rc=0 || rc=$?
  [ "$rc" -ne 0 ]
}

@test "I6 (CYP-F9): non-hex fingerprint is rejected post-source" {
  # The fixture writer ensures a valid 12-char hex fingerprint, so the
  # init succeeds. We construct a hostile file with a malformed fingerprint
  # (12 chars but containing non-hex G-Z) — note the shape-gate regex
  # requires `[a-f0-9]{12}` so this is caught at the gate, not at the
  # post-source check. The post-source check is defense-in-depth for
  # hypothetical future shape-gate weakening.
  cat > "$MERGED" <<'EOF'
# version=1
# source-sha256=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
declare -gA LOA_MODEL_PROVIDERS=()
declare -gA LOA_MODEL_IDS=()
declare -gA LOA_MODEL_ENDPOINT_FAMILIES=()
declare -gA LOA_MODEL_COST_INPUT_PER_MTOK=()
declare -gA LOA_MODEL_COST_OUTPUT_PER_MTOK=()
LOA_OVERLAY_FINGERPRINT=GHIJKLMNOPQR
EOF
  : > "$LOCKFILE"
  source "$HELPER"
  run loa_overlay_init
  [ "$status" -eq 1 ]
}

@test "I7 (CYP-F10): malformed alias (with control chars) returns 1 from resolve" {
  _fixture_merged 1
  source "$HELPER"
  loa_overlay_init
  # Aliases with newlines, semicolons, brackets must be rejected.
  # Per BB iter-3 F4: use an array so embedded newlines (default IFS
  # would split $'foo\nbar' on the \n) are preserved.
  local hostile_inputs=(
    $'foo\nbar'
    "a;b"
    "[bracket]"
    "../traversal"
    ""
    "with space"
    $'tab\there'
    $'cr\rhere'
  )
  for hostile in "${hostile_inputs[@]}"; do
    run loa_overlay_resolve_provider_id "$hostile"
    [ "$status" -eq 1 ]
  done
}

@test "I8 (CYP-F10): dot-dot in alias is rejected" {
  _fixture_merged 1
  source "$HELPER"
  loa_overlay_init
  run loa_overlay_resolve_provider_id ".."
  [ "$status" -eq 1 ]
  run loa_overlay_resolve_provider_id "a..b"
  [ "$status" -eq 1 ]
}
